### ISSUE TITLE
[Bug]  Connection reset by peer

### ISSUE THREAD

**Issue by sfortis** [Vaskivskyi/ha-asusrouter#157]
### The problem

At random times, integration is disconnected from the router.

When this happen, all entities are frozen in time.

![image](https://user-images.githubusercontent.com/15342157/179385803-f6ac273f-dba5-44e7-abeb-e9b1627715d8.png)

Integration should try to recover and reconnect since https on the router is accepting connections. The only was to recover the integration is to restart ha.

Also, when this happens, diagnostic logs cannot be downloaded 

```
Logger: aiohttp.server
Source: custom_components/asusrouter/diagnostics.py:84
Integration: ASUS Router ([documentation](https://github.com/Vaskivskyi/ha-asusrouter), [issues](https://github.com/Vaskivskyi/ha-asusrouter/issues))
First occurred: 08:53:22 (4 occurrences)
Last logged: 08:54:39

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 222, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 79, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 236, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 136, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/diagnostics/__init__.py", line 211, in get
    data = await info[d_type.value](hass, config_entry)
  File "/config/custom_components/asusrouter/diagnostics.py", line 84, in async_get_config_entry_diagnostics
    "last_activity": device.last_activity,
AttributeError: 'AsusRouterDevInfo' object has no attribute 'last_activity'
```

### Your device model

RT-AC86U

### Firmware type

Merlin

### Firmware version

3.0.0.4.386.7_0

### Integration version with the issue

0.5.1

### Method of the integration installation

HACS

### What version and type of Home Assistant installation do you use

2022.7.5

### Is there anything useful in the logs?

```txt
2022-07-16 23:17:42 ERROR (MainThread) [asusrouter.asusrouter] [Errno 104] Connection reset by peer
2022-07-16 23:17:42 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
File "/usr/local/lib/python3.10/site-packages/asusrouter/connection.py", line 181, in async_request
async with self._session.post(
File "/usr/local/lib/python3.10/site-packages/aiohttp/client.py", line 1138, in __aenter__
self._resp = await self._coro
File "/usr/local/lib/python3.10/site-packages/aiohttp/client.py", line 559, in _request
await resp.start(conn)
File "/usr/local/lib/python3.10/site-packages/aiohttp/client_reqrep.py", line 893, in start
with self._timer:
File "/usr/local/lib/python3.10/site-packages/aiohttp/helpers.py", line 721, in __exit__
raise asyncio.TimeoutError from None
asyncio.exceptions.TimeoutError
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/usr/local/lib/python3.10/site-packages/asusrouter/connection.py", line 111, in async_run_command
result = await self.async_request(command, endpoint, self._headers)
File "/usr/local/lib/python3.10/site-packages/asusrouter/connection.py", line 257, in async_request
raise AsusRouterConnectionTimeoutError()
asusrouter.error.AsusRouterConnectionTimeoutError: None
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/config/custom_components/asusrouter/bridge.py", line 130, in async_get_connected_devices
api_devices = await self._api.async_get_devices()
File "/usr/local/lib/python3.10/site-packages/asusrouter/asusrouter.py", line 731, in async_get_devices
await self.async_monitor_devices()
File "/usr/local/lib/python3.10/site-packages/asusrouter/asusrouter.py", line 585, in async_monitor_devices
data = await self.async_hook(AR_HOOK_DEVICES)
File "/usr/local/lib/python3.10/site-packages/asusrouter/asusrouter.py", line 296, in async_hook
raise ex
File "/usr/local/lib/python3.10/site-packages/asusrouter/asusrouter.py", line 291, in async_hook
result = await self.connection.async_run_command(
File "/usr/local/lib/python3.10/site-packages/asusrouter/connection.py", line 117, in async_run_command
await self.async_connect()
File "/usr/local/lib/python3.10/site-packages/asusrouter/connection.py", line 181, in async_request
async with self._session.post(
File "/usr/local/lib/python3.10/site-packages/aiohttp/client.py", line 1138, in __aenter__
self._resp = await self._coro
File "/usr/local/lib/python3.10/site-packages/aiohttp/client.py", line 559, in _request
await resp.start(conn)
File "/usr/local/lib/python3.10/site-packages/aiohttp/client_reqrep.py", line 898, in start
message, payload = await protocol.read() # type: ignore[union-attr]
File "/usr/local/lib/python3.10/site-packages/aiohttp/streams.py", line 616, in read
await self._waiter
aiohttp.client_exceptions.ClientOSError: [Errno 104] Connection reset by peer
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
File "/config/custom_components/asusrouter/router.py", line 380, in update_all
await self.update_devices()
File "/config/custom_components/asusrouter/router.py", line 388, in update_devices
api_devices = await self._api.async_get_connected_devices()
File "/config/custom_components/asusrouter/bridge.py", line 132, in async_get_connected_devices
raise UpdateFailed(ex) from ex
homeassistant.helpers.update_coordinator.UpdateFailed: [Errno 104] Connection reset by peer
```

**Comment by Vaskivskyi** [comment]
Hello, @sfortis,

Thanks for your feedback! 👍🏻 

I am aware of this problem and am working on the fix. Unfortunately, I cannot yet guarantee any timeframe, but this bug has a high priority on the list of what to fix.

**Comment by sfortis** [comment]
@Vaskivskyi great 👍 maybe it has to do with the asus router itself which not allows multiple concurrent logins

https://www.snbforums.com/threads/how-to-allow-multiple-logins.10211/

btw. I've switched the integration to https and seems to be more stable. 2 days and still running...

**Comment by Vaskivskyi** [comment]
Yes, partially. You cannot login twice to the WebUI (will get "someone is already logged in"), but the limits for the mobile apps and the integration (which makes it look like an official app for the router) are a bit different. Depending on the firmware, several connections are possible. But let's say more new logins are detected - more old ones will be reset.

With newer devices, it happens not as often as with older ones but still happens.

**Comment by sfortis** [comment]
IDK if its a happy accident, but since switched the integration to https protocol, ive zero disconnections. I keep using routers UI on http. So far so good!

<img width="760" alt="image" src="https://user-images.githubusercontent.com/15342157/181807784-5a33ca37-814b-407f-aaa4-e3a9b8b009bc.png">

**Comment by Vaskivskyi** [comment]
Hey, @sfortis,

Thanks to your report I have found a problem with the integration Diagnostics module. It's already solved in PR #174 and will be released with the next integration version.

Thanks! 👍🏻 

Meanwhile, work on the issue itself is still in progress

**Comment by sfortis** [comment]
@Vaskivskyi  great news! thanks for your work on this

**Comment by Vaskivskyi** [comment]
Hi, @sfortis,

Can you still get into the `Connection reset by peer` error? With the latest version (0.6.0) integration became more stable

**Comment by Vaskivskyi** [comment]
@sfortis,

Good! 👍🏻  I'm happy to help.

If you will experience any other issues or even the same disconnection issue, please open a new [bug report](https://github.com/Vaskivskyi/ha-asusrouter/issues/new/choose), so it will be easier for me to keep track of the things
