### ISSUE TITLE
[Bug] Device tracking is unreliable during longer periods of time. ha-asusrouter never recovers from AsusRouterServerDisconnectedError

### ISSUE THREAD

**Issue by rkkoszewski** [Vaskivskyi/ha-asusrouter#184]
### The problem

Hi, so this seems to be happening since a long time now. Whenever my Home Assistant instance is running during longer periods of time (And by that I mean more than 2 or 3 days), the device tracking part of ha-asusrouter stops working and never recovers until I eider restart the component or restart HA all together. The tracking of WiFi stats, CPU usage, network transfer, etc still seems to be updating, but the tracking of devices stops working.

Looking at the logs I see this:

```
Logger: homeassistant
Source: custom_components/asusrouter/bridge.py:132
Integration: ASUS Router (documentation, issues)
First occurred: 5:50:43 AM (1 occurrences)
Last logged: 5:50:43 AM

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/asusrouter/connection.py", line 181, in async_request
    async with self._session.post(
  File "/usr/local/lib/python3.10/site-packages/aiohttp/client.py", line 1138, in __aenter__
    self._resp = await self._coro
  File "/usr/local/lib/python3.10/site-packages/aiohttp/client.py", line 559, in _request
    await resp.start(conn)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/client_reqrep.py", line 898, in start
    message, payload = await protocol.read()  # type: ignore[union-attr]
  File "/usr/local/lib/python3.10/site-packages/aiohttp/streams.py", line 616, in read
    await self._waiter
aiohttp.client_exceptions.ServerDisconnectedError: Server disconnected

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/asusrouter/bridge.py", line 130, in async_get_connected_devices
    api_devices = await self._api.async_get_devices()
  File "/usr/local/lib/python3.10/site-packages/asusrouter/asusrouter.py", line 731, in async_get_devices
    await self.async_monitor_devices()
  File "/usr/local/lib/python3.10/site-packages/asusrouter/asusrouter.py", line 585, in async_monitor_devices
    data = await self.async_hook(AR_HOOK_DEVICES)
  File "/usr/local/lib/python3.10/site-packages/asusrouter/asusrouter.py", line 296, in async_hook
    raise ex
  File "/usr/local/lib/python3.10/site-packages/asusrouter/asusrouter.py", line 291, in async_hook
    result = await self.connection.async_run_command(
  File "/usr/local/lib/python3.10/site-packages/asusrouter/connection.py", line 114, in async_run_command
    raise ex
  File "/usr/local/lib/python3.10/site-packages/asusrouter/connection.py", line 111, in async_run_command
    result = await self.async_request(command, endpoint, self._headers)
  File "/usr/local/lib/python3.10/site-packages/asusrouter/connection.py", line 260, in async_request
    raise AsusRouterServerDisconnectedError()
asusrouter.error.AsusRouterServerDisconnectedError: Server disconnected

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/asusrouter/router.py", line 390, in update_all
    await self.update_devices()
  File "/config/custom_components/asusrouter/router.py", line 398, in update_devices
    api_devices = await self._api.async_get_connected_devices()
  File "/config/custom_components/asusrouter/bridge.py", line 132, in async_get_connected_devices
    raise UpdateFailed(ex) from ex
homeassistant.helpers.update_coordinator.UpdateFailed: Server disconnected
```

I'm not sure how ha-asusrouter handles the connection to the router, but if the connection fails it should retry to connect in a few seconds. I've been tinkering myself with the AsusWRT DUT API, and I noticed that there are times where the server just freezes for a while, and at times I've seen the whole service crash for a few seconds on the router, where not even the official AsusWRT mobile app works (But it usually always recovers after some time). Perhaps ha-asusrouter is hitting one of these cases, although being network, one should assume that anything can fail along the way.

### Your device model

RT-AX86U

### Firmware type

Merlin

### Firmware version

386.7_2

### Integration version with the issue

0.6.0

### Method of the integration installation

HACS

### What version and type of Home Assistant installation do you use

Home Assistant 2022.8.3

**Comment by Vaskivskyi** [comment]
Hi, @rkkoszewski,

Thanks for your feedback! :+1:

I am aware of this issue and it is in the priority list for a fix. Unfortunately, it is not easy to reproduce on my device (RT-AX88U), so it takes much longer then I expected to test everything out.

I hope to finish work on it by the end of August.

**Comment by rkkoszewski** [comment]
Awesome! Thank you as always @Vaskivskyi for looking into it!

**Comment by Vaskivskyi** [comment]
Just letting you know, that work is still in progress, I didn't forget about this bug 🙂 . It has happened only twice on my device, so debugging the case is a bit painful and time-consuming

**Comment by Vaskivskyi** [comment]
Hey, @rkkoszewski,

I think you would like version 0.8.0 - no more `server disconnected` errors. And no sensors should be stuck.

**Comment by rkkoszewski** [comment]
Thank you so much @Vaskivskyi for finding and fixing the issue. This is really amazing news!! I'll test it out as soon as I'm back home!

**Comment by Vaskivskyi** [comment]
Hello, @rkkoszewski,

Did you have a chance to test the new version? Does it work now as you would expect?

**Comment by rkkoszewski** [comment]
Sorry I'm currently on vacations for a month. I updated the extension and have seen no issues so far, but given that I'm currently not at home I cannot test it in depth.

I'm closing the bug as it seems to have been mitigated. If I see the issue still occuring in the future, I'll reopen the bug and add some fresh logs to it.

Thank you for looking into and fixing the issue @Vaskivskyi !! 

I hope this plugin will replace the official AsusWRT plugin some day. It's miles ahead already!
