### ISSUE TITLE
[Bug] Unable to get information: Maximum recusion depth

### ISSUE THREAD

**Issue by LouPaloma** [Vaskivskyi/ha-asusrouter#223]
### The problem

This issue appears and prevents any data (except temperatures?) from being displayed.  There are no issues with the router UI, although the supplied asuswrt integration would also sometimes fail (which is why I switched) with something like:

`
[homeassistant.components.asuswrt.router] Unexpected error fetching sensors_rates data: '<' not supported between instances of 'NoneType' and 'float'
`

This error originated from a custom integration.

Logger: custom_components.asusrouter.router
Source: deps/lib/python3.9/site-packages/asusrouter/asusrouter.py:346
Integration: ASUS Router (documentation, issues)
First occurred: 5:02:01 AM (250 occurrences)
Last logged: 3:14:34 PM

`Unexpected error fetching wlan data: maximum recursion depth exceeded while calling a Python object
Traceback (most recent call last):
  File "/root/miniconda3/envs/hass-py39/lib/python3.9/site-packages/homeassistant/helpers/update_coordinator.py", line 205, in _async_refresh
    self.data = await self._async_update_data()
  File "/root/miniconda3/envs/hass-py39/lib/python3.9/site-packages/homeassistant/helpers/update_coordinator.py", line 164, in _async_update_data
    return await self.update_method()
  File "/opt/homeassistant/custom_components/asusrouter/bridge.py", line 297, in _get_wlan
    data = await self._api.async_get_wlan()
  File "/opt/homeassistant/deps/lib/python3.9/site-packages/asusrouter/asusrouter.py", line 967, in async_get_wlan
    ids = await self.async_get_wlan_ids()
  File "/opt/homeassistant/deps/lib/python3.9/site-packages/asusrouter/asusrouter.py", line 987, in async_get_wlan_ids
    interfaces = await self.async_get_network_labels()
  File "/opt/homeassistant/deps/lib/python3.9/site-packages/asusrouter/asusrouter.py", line 786, in async_get_network_labels
    return await self.async_get_network_labels()
  File "/opt/homeassistant/deps/lib/python3.9/site-packages/asusrouter/asusrouter.py", line 786, in async_get_network_labels
    return await self.async_get_network_labels()
  File "/opt/homeassistant/deps/lib/python3.9/site-packages/asusrouter/asusrouter.py", line 786, in async_get_network_labels
    return await self.async_get_network_labels()
  [Previous line repeated 974 more times]
  File "/opt/homeassistant/deps/lib/python3.9/site-packages/asusrouter/asusrouter.py", line 778, in async_get_network_labels
    await self.async_monitor_main()
  File "/opt/homeassistant/deps/lib/python3.9/site-packages/asusrouter/asusrouter.py", line 346, in async_monitor_main
    await asyncio.sleep(DEFAULT_SLEEP_TIME)
  File "/root/miniconda3/envs/hass-py39/lib/python3.9/asyncio/tasks.py", line 651, in sleep
    h = loop.call_later(delay,
  File "/root/miniconda3/envs/hass-py39/lib/python3.9/asyncio/base_events.py", line 714, in call_later
    timer = self.call_at(self.time() + delay, callback, *args,
  File "/root/miniconda3/envs/hass-py39/lib/python3.9/asyncio/base_events.py", line 729, in call_at
    timer = events.TimerHandle(when, callback, args, self, context)
  File "/root/miniconda3/envs/hass-py39/lib/python3.9/asyncio/events.py", line 105, in __init__
    super().__init__(callback, args, loop, context)
  File "/root/miniconda3/envs/hass-py39/lib/python3.9/asyncio/events.py", line 33, in __init__
    context = contextvars.copy_context()
RecursionError: maximum recursion depth exceeded while calling a Python object
`

### Your device model

RT-AC86U

### Firmware type

Merlin

### Firmware version

386.7_2

### Integration version with the issue

0.8.0

### Method of the integration installation

HACS

### What version and type of Home Assistant installation do you use

2022.9.2

### Is there anything useful in the logs?

```txt
2022-09-14 15:12:26.463 ERROR (MainThread) [custom_components.asusrouter.router] Unexpected error fetching wlan data: maximum recursion depth exceeded while calling a Python object
Traceback (most recent call last):
  File "/root/miniconda3/envs/hass-py39/lib/python3.9/site-packages/homeassistant/helpers/update_coordinator.py", line 205, in _async_refresh
    self.data = await self._async_update_data()
  File "/root/miniconda3/envs/hass-py39/lib/python3.9/site-packages/homeassistant/helpers/update_coordinator.py", line 164, in _async_update_data
    return await self.update_method()
  File "/opt/homeassistant/custom_components/asusrouter/bridge.py", line 297, in _get_wlan
    data = await self._api.async_get_wlan()
  File "/opt/homeassistant/deps/lib/python3.9/site-packages/asusrouter/asusrouter.py", line 967, in async_get_wlan
    ids = await self.async_get_wlan_ids()
  File "/opt/homeassistant/deps/lib/python3.9/site-packages/asusrouter/asusrouter.py", line 987, in async_get_wlan_ids
    interfaces = await self.async_get_network_labels()
  File "/opt/homeassistant/deps/lib/python3.9/site-packages/asusrouter/asusrouter.py", line 786, in async_get_network_labels
    return await self.async_get_network_labels()
  File "/opt/homeassistant/deps/lib/python3.9/site-packages/asusrouter/asusrouter.py", line 786, in async_get_network_labels
    return await self.async_get_network_labels()
  File "/opt/homeassistant/deps/lib/python3.9/site-packages/asusrouter/asusrouter.py", line 786, in async_get_network_labels
    return await self.async_get_network_labels()
  [Previous line repeated 974 more times]
  File "/opt/homeassistant/deps/lib/python3.9/site-packages/asusrouter/asusrouter.py", line 778, in async_get_network_labels
    await self.async_monitor_main()
  File "/opt/homeassistant/deps/lib/python3.9/site-packages/asusrouter/asusrouter.py", line 346, in async_monitor_main
    await asyncio.sleep(DEFAULT_SLEEP_TIME)
  File "/root/miniconda3/envs/hass-py39/lib/python3.9/asyncio/tasks.py", line 651, in sleep
    h = loop.call_later(delay,
  File "/root/miniconda3/envs/hass-py39/lib/python3.9/asyncio/base_events.py", line 714, in call_later
    timer = self.call_at(self.time() + delay, callback, *args,
  File "/root/miniconda3/envs/hass-py39/lib/python3.9/asyncio/base_events.py", line 729, in call_at
    timer = events.TimerHandle(when, callback, args, self, context)
  File "/root/miniconda3/envs/hass-py39/lib/python3.9/asyncio/events.py", line 105, in __init__
    super().__init__(callback, args, loop, context)
  File "/root/miniconda3/envs/hass-py39/lib/python3.9/asyncio/events.py", line 33, in __init__
    context = contextvars.copy_context()
RecursionError: maximum recursion depth exceeded while calling a Python object
```

**Comment by Vaskivskyi** [comment]
Hello, @LouPaloma,

Thanks for your feedback! 👍🏻 

I am sorry, that the integration does not work well for you. So none of the sensors, except for temperatures is working? What about device trackers?

The RecursionError in your log is a result of not being able to get a response from the device. In this case, the library for communications tries to repeat requests. Of course, in principle, it might get into a too-long recursion, but I have not observed it yet.

I suggest you try the following:

1. Reboot your router. I know, this is a frustrating suggestion, but some firmware and devices are known to stop responding on different API endpoints after several days or weeks. If the device reboot is possible, please also reload the integration (no need to restart HA fully). If everything is the same, proceed.
2. Enable debug logging for the integration and library. You will need to add the following yaml code to your `configuration.yaml`. You will need to restart HA for changes to take effect.

```yaml
logger:
  logs:
    custom_components.asusrouter: debug
    asusrouter: debug
```

3. Please keep track of the log for at least 5-10 minutes. I would need at least a couple of errors recorded for different API endpoints and different methods executed by the library and the integration. Save the log as a text file and send it to me via Yevhenii@Vaskivskyi.com or to https://t.me/Vaskivskyi.

The following steps will depend on these 3.

Thanks for your help in making this integration better! 👍🏻

**Comment by LouPaloma** [comment]
Thanks.  Debug has been turned on.

I did notice that an update needed to be applied via HA reboot.  I have been running for 24+ hours now without an issue.  Perhaps there was a conflict.

I will monitor for 7 days and close this if I do not see any more issues by then.  Otherwise, I'll post debug log information.

BTW:  is there a way to turn on additional diagnostic information?

**Comment by Vaskivskyi** [comment]
Hello,

Did you experience such an issue again? If not, that might really be just a coincidence.

What kind of additional diagnostic information you are interested in? AsusRouter is still under work to make it as usable and as stable as possible, so I am open to any suggestions which might help.

**Comment by LouPaloma** [comment]
This looks to be working now.  I suspect it was the version conflict.
