### ISSUE TITLE
[Bug] Connection reset by peer

### ISSUE THREAD

**Issue by qiusj** [Vaskivskyi/ha-asusrouter#226]
### The problem

When http service on router is restart, the component can not re-connect web server.
After reload the component, all entities are unavalibe.

### Your device model

ZenWiFi AX Mini (XD4)

### Firmware type

Stock

### Firmware version

3.0.0.4.386_49599

### Integration version with the issue

0.8.0

### Method of the integration installation

HACS

### What version and type of Home Assistant installation do you use

Core  2022.8.7

### Is there anything useful in the logs?

```txt
2022-09-23 16:50:11.395 ERROR (MainThread) [custom_components.asusrouter.router] Error requesting misc data: [Errno 104] Connection reset by peer
2022-09-23 16:50:11.400 ERROR (MainThread) [custom_components.asusrouter.router] Error fetching wlan data: [Errno 104] Connection reset by peer
2022-09-23 16:50:11.413 ERROR (MainThread) [custom_components.asusrouter.router] Error fetching cpu data: [Errno 104] Connection reset by peer
2022-09-23 16:50:11.416 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
File "/usr/local/lib/python3.10/site-packages/asusrouter/connection.py", line 179, in async_request
async with self._session.post(
File "/usr/local/lib/python3.10/site-packages/aiohttp/client.py", line 1138, in __aenter__
self._resp = await self._coro
File "/usr/local/lib/python3.10/site-packages/aiohttp/client.py", line 559, in _request
await resp.start(conn)
File "/usr/local/lib/python3.10/site-packages/aiohttp/client_reqrep.py", line 893, in start
with self._timer:
File "/usr/local/lib/python3.10/site-packages/aiohttp/helpers.py", line 721, in __exit__
raise asyncio.TimeoutError from None
asyncio.exceptions.TimeoutError
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/usr/local/lib/python3.10/site-packages/asusrouter/connection.py", line 112, in async_run_command
result = await self.async_request(command, endpoint, self._headers)
File "/usr/local/lib/python3.10/site-packages/asusrouter/connection.py", line 255, in async_request
raise AsusRouterConnectionTimeoutError()
asusrouter.error.AsusRouterConnectionTimeoutError: None
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/config/custom_components/asusrouter/bridge.py", line 137, in async_get_connected_devices
api_devices = await self._api.async_get_devices()
File "/usr/local/lib/python3.10/site-packages/asusrouter/asusrouter.py", line 740, in async_get_devices
await self.async_monitor_devices()
File "/usr/local/lib/python3.10/site-packages/asusrouter/asusrouter.py", line 594, in async_monitor_devices
data = await self.async_hook(AR_HOOK_DEVICES)
File "/usr/local/lib/python3.10/site-packages/asusrouter/asusrouter.py", line 305, in async_hook
raise ex
File "/usr/local/lib/python3.10/site-packages/asusrouter/asusrouter.py", line 300, in async_hook
result = await self.connection.async_run_command(
File "/usr/local/lib/python3.10/site-packages/asusrouter/connection.py", line 118, in async_run_command
await self.async_connect()
File "/usr/local/lib/python3.10/site-packages/asusrouter/connection.py", line 179, in async_request
async with self._session.post(
File "/usr/local/lib/python3.10/site-packages/aiohttp/client.py", line 1138, in __aenter__
self._resp = await self._coro
File "/usr/local/lib/python3.10/site-packages/aiohttp/client.py", line 559, in _request
await resp.start(conn)
File "/usr/local/lib/python3.10/site-packages/aiohttp/client_reqrep.py", line 898, in start
message, payload = await protocol.read() # type: ignore[union-attr]
File "/usr/local/lib/python3.10/site-packages/aiohttp/streams.py", line 616, in read
await self._waiter
aiohttp.client_exceptions.ClientOSError: [Errno 104] Connection reset by peer
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
File "/config/custom_components/asusrouter/router.py", line 397, in update_all
await self.update_devices()
File "/config/custom_components/asusrouter/router.py", line 405, in update_devices
api_devices = await self._api.async_get_connected_devices()
File "/config/custom_components/asusrouter/bridge.py", line 139, in async_get_connected_devices
raise UpdateFailed(ex) from ex
homeassistant.helpers.update_coordinator.UpdateFailed: [Errno 104] Connection reset by peer


Router's logs:

Sep 23 16:50:10 HTTPD: waitting 10 minitues and restart
Sep 23 16:50:10 rc_service: httpd 2211:notify_rc restart_httpd
Sep 23 16:50:10 ZenWiFi_XD4: start httpd:80
Sep 23 16:50:10 httpd: Save SSL certificate...80
Sep 23 16:50:10 httpd: mssl_cert_key_match : PASS
Sep 23 16:50:10 httpd: Succeed to init SSL certificate...80
```

**Comment by Vaskivskyi** [comment]
Hello, @qiusj,

Thank you for your feedback! 👍🏻 

It is surprising, that the integration cannot reconnect after the HTTP server is restarted. I'll check it out and let you know if any more information is needed from your side.

**Comment by Vaskivskyi** [comment]
Please, check the new version 0.8.1, which is already available through HACS. The "Connection reset by peer" problem should now be solved.

**Comment by qiusj** [comment]
> 

It's OK now. thanks.
