### ISSUE TITLE
[Bug] Latest version 0.11.2 throws errors, no data being collected

### ISSUE THREAD

**Issue by RealGandy** [Vaskivskyi/ha-asusrouter#317]
### The problem

Latest version shows following on integrations screen:

![image](https://user-images.githubusercontent.com/305484/199451531-61095b40-eedf-4f4a-b465-4001155a7cb2.png)

Log file shows this error;

`2022-11-02 09:15:03.345 WARNING (MainThread) [homeassistant.config_entries] Config entry '192.168.2.1' for asusrouter integration not ready yet: 'NoneType' object is not subscriptable; Retrying in background`

Existing items do not update and are shown as unavailable

Regressing to 0.11.0 resolves the issue

### Your device model

DSL-AC68U

### Firmware type

Merlin

### Firmware version

386.04-gnuton2

### Integration version with the issue

0.11.2

### Method of the integration installation

HACS

### What version and type of Home Assistant installation do you use

Container.  Home Assistant Core 2022.10.5

### Is there anything useful in the logs?

```txt
2022-11-02 09:21:26.510 WARNING (MainThread) [homeassistant.config_entries] Config entry '192.168.2.1' for asusrouter integration not ready yet: 'NoneType' object is not subscriptable; Retrying in background
2022-11-02 09:21:34.532 DEBUG (MainThread) [asusrouter.connection] No certificate provided. Using trusted
2022-11-02 09:21:35.937 DEBUG (MainThread) [asusrouter.connection] Login successful on port 8443: {'Model_Name': 'DSL-AC68U', 'AiHOMEAPILevel': '21', 'Httpd_AiHome_Ver': '0'}
2022-11-02 09:21:35.937 DEBUG (MainThread) [asusrouter.asusrouter] Identifying the device
2022-11-02 09:21:35.937 DEBUG (MainThread) [asusrouter.connection] Started command hook=nvram_get(serial_no);nvram_get(label_mac);nvram_get(productid);nvram_get(firmver);nvram_get(buildno);nvram_get(extendno);nvram_get(rc_support);nvram_get(ss_support);nvram_get(led_val);
2022-11-02 09:21:36.158 DEBUG (MainThread) [asusrouter.asusrouter] Hook was sent successfully: nvram_get(serial_no);nvram_get(label_mac);nvram_get(productid);nvram_get(firmver);nvram_get(buildno);nvram_get(extendno);nvram_get(rc_support);nvram_get(ss_support);nvram_get(led_val);
2022-11-02 09:21:46.160 DEBUG (MainThread) [asusrouter.connection] No certificate provided. Using trusted
2022-11-02 09:21:46.293 DEBUG (MainThread) [asusrouter.connection] Login successful on port 8443: {'Model_Name': 'DSL-AC68U', 'AiHOMEAPILevel': '21', 'Httpd_AiHome_Ver': '0'}
2022-11-02 09:21:46.293 DEBUG (MainThread) [asusrouter.asusrouter] Identifying the device
2022-11-02 09:21:46.294 DEBUG (MainThread) [asusrouter.connection] Started command hook=nvram_get(serial_no);nvram_get(label_mac);nvram_get(productid);nvram_get(firmver);nvram_get(buildno);nvram_get(extendno);nvram_get(rc_support);nvram_get(ss_support);nvram_get(led_val);
2022-11-02 09:21:46.776 DEBUG (MainThread) [asusrouter.asusrouter] Hook was sent successfully: nvram_get(serial_no);nvram_get(label_mac);nvram_get(productid);nvram_get(firmver);nvram_get(buildno);nvram_get(extendno);nvram_get(rc_support);nvram_get(ss_support);nvram_get(led_val);
2022-11-02 09:22:06.778 DEBUG (MainThread) [asusrouter.connection] No certificate provided. Using trusted
2022-11-02 09:22:06.865 DEBUG (MainThread) [asusrouter.connection] Login successful on port 8443: {'Model_Name': 'DSL-AC68U', 'AiHOMEAPILevel': '21', 'Httpd_AiHome_Ver': '0'}
2022-11-02 09:22:06.865 DEBUG (MainThread) [asusrouter.asusrouter] Identifying the device
2022-11-02 09:22:06.866 DEBUG (MainThread) [asusrouter.connection] Started command hook=nvram_get(serial_no);nvram_get(label_mac);nvram_get(productid);nvram_get(firmver);nvram_get(buildno);nvram_get(extendno);nvram_get(rc_support);nvram_get(ss_support);nvram_get(led_val);
2022-11-02 09:22:06.980 DEBUG (MainThread) [asusrouter.asusrouter] Hook was sent successfully: nvram_get(serial_no);nvram_get(label_mac);nvram_get(productid);nvram_get(firmver);nvram_get(buildno);nvram_get(extendno);nvram_get(rc_support);nvram_get(ss_support);nvram_get(led_val);
```

### Diagnostics information

diagnostics options not available

**Comment by Vaskivskyi** [comment]
Hey @RealGandy,

I am sorry to hear, you are experiencing problems with the integration.

Can you please retry this with logging for integration set to debug as well as the `asusrouter` library?

```
logger:
    logs:
        custom_components.asusrouter: debug
        asusrouter: debug
```

Or was it already set? Was there any debug message from `custom_components.asusrouter`?

**Comment by RealGandy** [comment]
Sorry, yes both of those components were set to debug and the lines above are the only entries seen in the log containing 'asus'

**Comment by CykloneFij** [comment]
I have exactly the same error: Retrying setup: 'NoneType' object is not subscriptable

This happened after updating the HACS integration from 0.11.0 to 0.11.2

HACS install
Asus ZenWiFi XT8
Merlin 386.07_2-gnuton1
Home Assistant Core 10.5
  Supervisor 2022.10.0
  Operating System 9.3

**Comment by Vaskivskyi** [comment]
Hey, @RealGandy, @CykloneFij,

Could you please check whether you can collect device identity using the latest version of the `asusrouter` library? You would need Python and `asusrouter` being the latest version. You can either use the venv of HA with the integration 0.11.2 for that or just manually install the library in any other environment using: `pip install asusrouter==0.10.3`. Then you would need to create a `script.py` file with this code and run it using `python script.py`.

In code please change `_host`, `_username` and `_password` to your values.

<details>
<summary>Code</summary>

```Python
"""Small test for available data from your AsusRouter"""

from asusrouter import AsusRouter
import asyncio


async def gather_data(host, username, password, use_ssl):
    """Method to gather all the known data"""

    # Initialize
    router = AsusRouter(host = host, username = username, password = password, use_ssl = use_ssl)

    try:
        # Connect and identify
        await router.connection.async_connect()

        await router.async_identify()
        print(router._identity)

        # Disconnect
        await router.connection.async_disconnect()
    except Exception as ex:
        raise ex


loop = asyncio.get_event_loop()

# Please, put your values in here
_host = "IP_or_hostname_here"
_username = "admin"
_password = "password"
_use_ssl = True

loop.run_until_complete(gather_data(_host, _username, _password, _use_ssl))

loop.close()
```

</details>

❗ **If it runs successfully, don't copy-paste the message here** - it will contain the MAC and the serial number of your device.

But, it will probably crash, so please copy the error trace here. Thanks!

**Comment by RealGandy** [comment]
```
/config/testing/script.py:26: DeprecationWarning: There is no current event loop
  loop = asyncio.get_event_loop()
Traceback (most recent call last):
  File "/config/testing/script.py", line 34, in <module>
    loop.run_until_complete(gather_data(_host, _username, _password, _use_ssl))
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/config/testing/script.py", line 23, in gather_data
    raise ex
  File "/config/testing/script.py", line 17, in gather_data
    await router.async_identify()
  File "/usr/local/lib/python3.10/site-packages/asusrouter/asusrouter.py", line 225, in async_identify
    identity["firmware"] = parsers.firmware_string(f"{identity['fw_major']}.{identity['fw_minor']}.{identity['fw_build']}")
  File "/usr/local/lib/python3.10/site-packages/asusrouter/util/parsers.py", line 606, in firmware_string
    major = string[1]
TypeError: 'NoneType' object is not subscriptable
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f2b90d05090>

```

**Comment by Vaskivskyi** [comment]
Ok, so something is wrong with the firmware version. Can you please try this as well?

<details>
<summary>Code</summary>

```Python
"""Small test for available data from your AsusRouter"""

from asusrouter import AsusRouter
import asyncio


async def gather_data(host, username, password, use_ssl):
    """Method to gather all the known data"""

    # Initialize
    router = AsusRouter(host = host, username = username, password = password, use_ssl = use_ssl)

    try:
        # Connect
        await router.connection.async_connect()

        # Get raw FW data
        version = await router.async_hook("nvram_get(firmver);nvram_get(buildno);nvram_get(extendno);")
        print(version)

        # Disconnect
        await router.connection.async_disconnect()
    except Exception as ex:
        raise ex


loop = asyncio.get_event_loop()

# Please, put your values in here
_host = "IP_or_hostname_here"
_username = "admin"
_password = "password"
_use_ssl = True

loop.run_until_complete(gather_data(_host, _username, _password, _use_ssl))

loop.close()
```
</details>

The output in the console will be similar to:
`{'firmver': '3.0.0.4', 'buildno': '386.8', 'extendno': '0'}`

**Comment by RealGandy** [comment]
```
config/testing/script2.py:27: DeprecationWarning: There is no current event loop
  loop = asyncio.get_event_loop()
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7fba8a2bd120>
{'firmver': '3.0.0.4', 'buildno': '386.04', 'extendno': '0-gnuton2'}

```

**Comment by Vaskivskyi** [comment]
Great, thanks! That should help. I will let you know if something else is needed

**Comment by Vaskivskyi** [comment]
@RealGandy, @CykloneFij,

Please, check the new version 0.11.3, which is already available via HACS

**Comment by CykloneFij** [comment]
@Vaskivskyi 
Thank you!  That works now with the 0.11.3.
All sensors and entities showing

**Comment by RealGandy** [comment]
Yup, all good for me too.

Many thanks for such a prompt response.
