### ISSUE TITLE
KeyError: 'connection_type' in 0.12.0

### ISSUE THREAD

**Issue by ehendrix23** [Vaskivskyi/ha-asusrouter#336]
### The problem

I just updated to 0.12.0 from 0.11.3 and now it fails when starting HA:

```
2022-11-14 16:32:42.998 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry 192.168.1.1 for asusrouter
Traceback (most recent call last):
  File "/Users/Media/homeassistant/lib/python3.9/site-packages/homeassistant/config_entries.py", line 357, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/Users/Media/hass_config/custom_components/asusrouter/__init__.py", line 40, in async_setup_entry
    await router.setup()
  File "/Users/Media/hass_config/custom_components/asusrouter/router.py", line 451, in setup
    await self.update_devices()
  File "/Users/Media/hass_config/custom_components/asusrouter/router.py", line 505, in update_devices
    device.update(dev_info, consider_home, event_call=self.fire_event)
  File "/Users/Media/hass_config/custom_components/asusrouter/router.py", line 230, in update
    ] = self._extra_state_attributes[DEVICE_ATTRIBUTE_CONNECTION_TYPE]
KeyError: 'connection_type'
```

Seems to be related to changes in #323 

### Your device model

ZenWiFi AX

### Firmware type

Stock

### Firmware version

3.0.0.4.388_21099

### Integration version with the issue

0.12.0

### Method of the integration installation

HACS

### What version and type of Home Assistant installation do you use

Core 2022.8.7

### Is there anything useful in the logs?

```txt
2022-11-14 16:32:42.998 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry 192.168.1.1 for asusrouter
Traceback (most recent call last):
  File "/Users/Media/homeassistant/lib/python3.9/site-packages/homeassistant/config_entries.py", line 357, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/Users/Media/hass_config/custom_components/asusrouter/__init__.py", line 40, in async_setup_entry
    await router.setup()
  File "/Users/Media/hass_config/custom_components/asusrouter/router.py", line 451, in setup
    await self.update_devices()
  File "/Users/Media/hass_config/custom_components/asusrouter/router.py", line 505, in update_devices
    device.update(dev_info, consider_home, event_call=self.fire_event)
  File "/Users/Media/hass_config/custom_components/asusrouter/router.py", line 230, in update
    ] = self._extra_state_attributes[DEVICE_ATTRIBUTE_CONNECTION_TYPE]
KeyError: 'connection_type'
```
```


### Diagnostics information

_No response_

### Additional information

_No response_

**Comment by ehendrix23** [comment]
I added the following line:
```_LOGGER.warning(f"Connection type for {self._ip} is: {con_type}")```

and I then get in my log file:
```Connection type for 192.168.1.31 is: 3```

On my router I have WIRED, 2.4G and 2 5G. That one is connected to my 2nd 5Ghz.

**Comment by Vaskivskyi** [comment]
Thanks a lot for your report and PR! 👍🏻

**Comment by Vaskivskyi** [comment]
0.12.1 is already released and fixes the issue.

The `5 GHz` and `5 GHz-2` networks are now also distinguished (which I have added after your PR) - this feature was requested by some users and can be quite useful.

Please, let me know whether 0.12.1 works well for you

**Comment by ehendrix23** [comment]
Just installed and restarted. No issues seen so I would say it is working. :-)

Thx for the quick release of an update.
