### ISSUE TITLE
[Bug] Errors thrown in log

### ISSUE THREAD

**Issue by RealGandy** [Vaskivskyi/ha-asusrouter#369]
### The problem

Following errors are thrown in the log, most of the devices seen to be discovered/created as expected, but maybe there’s some new functionality I’m missing?

### Your device model

DSL-AC68U

### Firmware type

Merlin

### Firmware version

3.0.0.4.386.7_2-gnuton1

### Integration version with the issue

0.14.2

### Method of the integration installation

HACS

### What version and type of Home Assistant installation do you use

Container 2022.11.5

### Is there anything useful in the logs?

```txt
2022-12-06 22:34:10.587 ERROR (MainThread) [custom_components.asusrouter.router] Unexpected error fetching parental_control data: list index out of range
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 205, in _async_refresh
    self.data = await self._async_update_data()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 164, in _async_update_data
    return await self.update_method()
  File "/config/custom_components/asusrouter/bridge.py", line 282, in _get_data_parental_control
    return await self._get_data(
  File "/config/custom_components/asusrouter/bridge.py", line 230, in _get_data
    raw = await method()
  File "/usr/local/lib/python3.10/site-packages/asusrouter/asusrouter.py", line 891, in async_get_parental_control
    data = parsers.parental_control(data)
  File "/usr/local/lib/python3.10/site-packages/asusrouter/util/parsers.py", line 457, in parental_control
    timemap=raw[AR_KEY_PARENTAL_CONTROL_TIMEMAP][i],
IndexError: list index out of range
2022-12-06 22:34:11.529 ERROR (MainThread) [custom_components.asusrouter.router] Unexpected error fetching parental_control data: list index out of range
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 205, in _async_refresh
    self.data = await self._async_update_data()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 164, in _async_update_data
    return await self.update_method()
  File "/config/custom_components/asusrouter/bridge.py", line 282, in _get_data_parental_control
    return await self._get_data(
  File "/config/custom_components/asusrouter/bridge.py", line 230, in _get_data
    raw = await method()
  File "/usr/local/lib/python3.10/site-packages/asusrouter/asusrouter.py", line 891, in async_get_parental_control
    data = parsers.parental_control(data)
  File "/usr/local/lib/python3.10/site-packages/asusrouter/util/parsers.py", line 457, in parental_control
    timemap=raw[AR_KEY_PARENTAL_CONTROL_TIMEMAP][i],
IndexError: list index out of range
2022-12-06 22:34:11.533 ERROR (MainThread) [homeassistant.components.switch] Error adding entities for domain switch with platform asusrouter
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 428, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 615, in _async_add_entity
    original_icon=entity.icon,
  File "/config/custom_components/asusrouter/entity.py", line 122, in icon
    if self.is_on:
  File "/config/custom_components/asusrouter/entity.py", line 115, in is_on
    return self.coordinator.data.get(self.entity_description.key)
AttributeError: 'NoneType' object has no attribute 'get'
2022-12-06 22:34:11.536 ERROR (MainThread) [homeassistant.components.switch] Error while setting up asusrouter platform for switch
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 289, in _async_setup_platform
    await asyncio.gather(*pending)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 428, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 615, in _async_add_entity
    original_icon=entity.icon,
  File "/config/custom_components/asusrouter/entity.py", line 122, in icon
    if self.is_on:
  File "/config/custom_components/asusrouter/entity.py", line 115, in is_on
    return self.coordinator.data.get(self.entity_description.key)
AttributeError: 'NoneType' object has no attribute 'get'
```

**Comment by Vaskivskyi** [comment]
Hey, @RealGandy,

Thank you for your report! 👍🏻 

The errors are connected to the [parental control functions](https://asusrouter.vaskivskyi.com/features/parental-control.html) implemented in version 0.12.0, so it might influence only those features and nothing else.

I will try to find the reason and fix it as soon as possible. Unfortunately, till December 17 I will not have access to the testing environment, so the fix might take a bit of time. Sorry for the inconvenience

**Comment by RealGandy** [comment]
Of course, no rush.

I do have parental controls set on a couple of devices, set to a time schedule if you want to check what you get back from the router for those.

Happy to run any code snippets to capture further info from my set up if required.

Cheers

**Comment by Vaskivskyi** [comment]
Please, check the latest 0.16.0 version. This issue should be fixed

**Comment by RealGandy** [comment]
All good now, thanks
