### ISSUE TITLE
RT-AX58U - Unknown Error on Setup

### ISSUE THREAD

**Issue by jazzyisj** [Vaskivskyi/ha-asusrouter#42]
Unable to set up an RT-AX58U.

This is all I get in the log - even with debug enabled.

```
2022-05-14 08:33:56 ERROR (MainThread) [custom_components.asusrouter.config_flow] Unknown error during connection for 192.168.1.1: 400, message='Expected HTTP/', url=URL('http://192.168.1.1:22000/login.cgi')
2022-05-14 08:33:56 ERROR (MainThread) [homeassistant] Error doing job: Unclosed client session
2022-05-14 08:33:56 ERROR (MainThread) [custom_components.asusrouter.config_flow] Some errors appear to happen
```

![image](https://user-images.githubusercontent.com/44064559/168426091-3075bb9e-2a16-4671-9a5b-50d251f0a21b.png)

**Comment by Vaskivskyi** [comment]
Hi, @jazzyisj,

Thanks for your feedback 👍🏻

You can enable debug logging for both the integration and the library for communication with the router. In your `configuration.yaml` for HA it should look like this:

```yaml
logger:
  logs:
    custom_components.asusrouter: debug
    asusrouter: debug
```

This will produce lots of everything in the log but could help find the problem. Unfortunately, 

Please, let me know what you will find.

**Comment by jazzyisj** [comment]
Config attempt using port 22000 (configured ssh port on router)
```
2022-05-14 13:09:36 DEBUG (MainThread) [asusrouter.connection] Certificate won't be checked
2022-05-14 13:09:36 ERROR (MainThread) [custom_components.asusrouter.config_flow] Unknown error during connection for 192.168.1.1: 400, message='Expected HTTP/', url=URL('http://192.168.1.1:22000/login.cgi')
2022-05-14 13:09:36 ERROR (MainThread) [homeassistant] Error doing job: Unclosed client session
2022-05-14 13:09:36 ERROR (MainThread) [custom_components.asusrouter.config_flow] Some errors appear to happen
```
Config attempt using default port.
```
2022-05-14 13:11:24 DEBUG (MainThread) [asusrouter.connection] Certificate won't be checked
2022-05-14 13:11:24 ERROR (MainThread) [custom_components.asusrouter.config_flow] Unknown error during connection for 192.168.1.1: ("Cannot connect to host 192.168.1.1:80 ssl:False [Connect call failed ('192.168.1.1', 80)]", None)
2022-05-14 13:11:24 ERROR (MainThread) [custom_components.asusrouter.config_flow] Some errors appear to happen
2022-05-14 13:11:25 ERROR (Recorder) [homeassistant] Error doing job: Unclosed client session
```
Config attempt default port w/SSL no verify
```
2022-05-14 16:10:09 DEBUG (MainThread) [asusrouter.connection] No certificate provided. Using trusted
2022-05-14 16:10:09 ERROR (MainThread) [custom_components.asusrouter.config_flow] Unknown error during connection for 192.168.1.1: ("Cannot connect to host 192.168.1.1:8443 ssl:True [Connect call failed ('192.168.1.1', 8443)]", None)
2022-05-14 16:10:09 ERROR (MainThread) [custom_components.asusrouter.config_flow] Some errors appear to happen
2022-05-14 16:10:09 ERROR (MainThread) [homeassistant] Error doing job: Unclosed client session
```
Config attempt port 22000 w/SSL no verify
```
2022-05-14 16:07:57 DEBUG (MainThread) [asusrouter.connection] Certificate won't be checked
2022-05-14 16:07:57 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 986, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1081, in create_connection
    transport, protocol = await self._create_connection_transport(
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1111, in _create_connection_transport
    await waiter
  File "/usr/local/lib/python3.9/asyncio/sslproto.py", line 528, in data_received
    ssldata, appdata = self._sslpipe.feed_ssldata(data)
  File "/usr/local/lib/python3.9/asyncio/sslproto.py", line 188, in feed_ssldata
    self._sslobj.do_handshake()
  File "/usr/local/lib/python3.9/ssl.py", line 944, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1129)
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/asusrouter/connection.py", line 127, in async_request
    async with self._session.post(
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client.py", line 1138, in __aenter__
    self._resp = await self._coro
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client.py", line 535, in _request
    conn = await self._connector.connect(
  File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 542, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 907, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 1175, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
  File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 990, in _wrap_create_connection
    raise ClientConnectorSSLError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorSSLError: Cannot connect to host 192.168.1.1:22000 ssl:False [[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1129)]
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/config/custom_components/asusrouter/bridge.py", line 162, in async_connect
    await self._api.connection.async_connect()
  File "/usr/local/lib/python3.9/site-packages/asusrouter/connection.py", line 228, in async_connect
    response = await self.async_request(payload = payload, endpoint = AR_PATH["login"], headers = headers, retry = retry)
  File "/usr/local/lib/python3.9/site-packages/asusrouter/connection.py", line 186, in async_request
    raise AsusRouterSSLError(str(ex)) from ex
asusrouter.error.AsusRouterSSLError: 
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/config/custom_components/asusrouter/config_flow.py", line 166, in _async_check_connection
    await api.async_connect()
  File "/config/custom_components/asusrouter/bridge.py", line 164, in async_connect
    raise ConfigEntryNotReady from ex
homeassistant.exceptions.ConfigEntryNotReady: 
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 100, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 79, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 219, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 137, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 205, in post
    return await super().post(request, flow_id)
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 62, in wrapper
    result = await method(view, request, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 109, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 260, in async_configure
    result = await self._async_handle_step(
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 335, in _async_handle_step
    result: FlowResult = await getattr(flow, method)(user_input)
  File "/config/custom_components/asusrouter/config_flow.py", line 201, in async_step_device
    check = await self._async_check_connection(user_input)
  File "/config/custom_components/asusrouter/config_flow.py", line 171, in _async_check_connection
    _LOGGER.error("Unknown error during connection for {}: {}".format(self._host, ex))
  File "/usr/src/homeassistant/homeassistant/exceptions.py", line 107, in __str__
    return super().__str__() or str(self.__cause__)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client_exceptions.py", line 339, in __str__
    "Cannot connect to host {0.host}:{0.port} ssl:{0.ssl} "
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client_exceptions.py", line 327, in host
    return self._conn_key.host
AttributeError: 'str' object has no attribute 'host'
```

**Comment by Vaskivskyi** [comment]
> Config attempt using port 22000 (configured ssh port on router)

The integration uses HTTP(S) API of AsusRouters, so that would explain why you got `400, message='Expected HTTP/'` - that was not a valid HTTP response, since the port is SSH. The same goes for the attempt (log 4) to connect with SSL.

Let's try to collect some more data. Do you mind entering your router web panel from the browser and checking what are the settings in `Administration - System - Local Access Config`? It has the following fields:

- `Authentication Method` - could be `HTTP` / `HTTPS` / `BOTH` (allowing both of them) - so we would know which method integration can use.
- `HTTPS LAN port` - defaults to 8443, but could be anything - important if HTTPS is enabled. No need to post it here - just remember it for the further tests.

Currently, I was able to reproduce this exact error only when trying to connect to the router offline:

`("Cannot connect to host ac66u.[redacted]:8443 ssl:True [Connect call failed ('[redacted]', 8443)]", None);`
