### ISSUE TITLE
AsusRouter integration won't start

### ISSUE THREAD

**Issue by pepe59** [Vaskivskyi/ha-asusrouter#443]
### The problem

After updating to the latest version 0.17.0, the AsusRouter does not start and there is an error in the HA log

```
Logger: homeassistant.config_entries
Source: helpers/entity_registry.py:695
First occurred: 21:58:55 (1 occurrences)
Last logged: 21:58:55

Error setting up entry 1xx.xx.1.x for asusrouter
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 382, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/asusrouter/__init__.py", line 24, in async_setup_entry
    await router.setup()
  File "/config/custom_components/asusrouter/router.py", line 680, in setup
    entity_reg.async_update_entity(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_registry.py", line 749, in async_update_entity
    return self._async_update_entity(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_registry.py", line 695, in _async_update_entity
    raise ValueError(
ValueError: Unique id 'asusrouter_xx:2c:xx:4a:xx:a8_temperature_cpu' is already in use by 'sensor.router_asus_temperature_cpu'
```

### Your device model

RT-AC68U

### Firmware type

Stock

### Firmware version

3.0.0.4.386_49703

### Integration version with the issue

0.17.0

### Method of the integration installation

HACS

### What version and type of Home Assistant installation do you use

Core 2023.1.1

**Comment by pepe59** [comment]
Defect removed.
I deleted the integration and created it again.
Everything works as expected.
Thanks for a great component

**Comment by Vaskivskyi** [comment]
Hey,

Sorry to hear, that integration did not manage to migrate properly between versions for you. But I am glad everything works well now.

In case you will experience any other problems, please, open a new issue.
