### ISSUE TITLE
Unable to connect

### ISSUE THREAD

**Issue by merlin-zaraza** [Vaskivskyi/ha-asusrouter#469]
### The problem

Logger: homeassistant.config_entries
Source: custom_components/asusrouter/bridge.py:246 
Integration: AsusRouter (documentation, issues) 
First occurred: 18:38:07 (1 occurrences) 
Last logged: 18:38:07

Error setting up entry 192.168.1.1 for asusrouter
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/asusrouter/connection.py", line 206, in async_request
    json_body = await r.json()
  File "/usr/src/homeassistant/homeassistant/helpers/aiohttp_client.py", line 52, in json
    return await super().json(*args, loads=loads, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/client_reqrep.py", line 1119, in json
    return loads(stripped.decode(encoding))
orjson.JSONDecodeError: unexpected end of data: line 2 column 18 (char 19)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/asusrouter/connection.py", line 114, in async_run_command
    result = await self.async_request(command, endpoint, self._headers)
  File "/usr/local/lib/python3.10/site-packages/asusrouter/connection.py", line 255, in async_request
    json_body = parsers.pseudo_json(text=string_body, page=endpoint)
  File "/usr/local/lib/python3.10/site-packages/asusrouter/util/parsers.py", line 550, in pseudo_json
    return json.loads(data.encode().decode("utf-8-sig"))
  File "/usr/local/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.10/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 1 column 21 (char 20)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/asusrouter/connection.py", line 206, in async_request
    json_body = await r.json()
  File "/usr/src/homeassistant/homeassistant/helpers/aiohttp_client.py", line 52, in json
    return await super().json(*args, loads=loads, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/client_reqrep.py", line 1119, in json
    return loads(stripped.decode(encoding))
orjson.JSONDecodeError: unexpected end of data: line 2 column 18 (char 19)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 382, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/asusrouter/__init__.py", line 24, in async_setup_entry
    await router.setup()
  File "/config/custom_components/asusrouter/router.py", line 731, in setup
    await self.update_devices()
  File "/config/custom_components/asusrouter/router.py", line 773, in update_devices
    api_devices = await self.bridge.async_get_connected_devices()
  File "/config/custom_components/asusrouter/bridge.py", line 263, in async_get_connected_devices
    return await self._get_data(self.api.async_get_devices)
  File "/config/custom_components/asusrouter/bridge.py", line 246, in _get_data
    raw = await method()
  File "/usr/local/lib/python3.10/site-packages/asusrouter/asusrouter.py", line 1037, in async_get_devices
    await self.async_monitor_devices()
  File "/usr/local/lib/python3.10/site-packages/asusrouter/asusrouter.py", line 816, in async_monitor_devices
    data = await self.async_hook(AR_HOOK_DEVICES)
  File "/usr/local/lib/python3.10/site-packages/asusrouter/asusrouter.py", line 363, in async_hook
    raise ex
  File "/usr/local/lib/python3.10/site-packages/asusrouter/asusrouter.py", line 359, in async_hook
    result = await self.connection.async_run_command(
  File "/usr/local/lib/python3.10/site-packages/asusrouter/connection.py", line 129, in async_run_command
    return await self.async_run_command(
  File "/usr/local/lib/python3.10/site-packages/asusrouter/connection.py", line 133, in async_run_command
    raise ex
  File "/usr/local/lib/python3.10/site-packages/asusrouter/connection.py", line 114, in async_run_command
    result = await self.async_request(command, endpoint, self._headers)
  File "/usr/local/lib/python3.10/site-packages/asusrouter/connection.py", line 255, in async_request
    json_body = parsers.pseudo_json(text=string_body, page=endpoint)
  File "/usr/local/lib/python3.10/site-packages/asusrouter/util/parsers.py", line 550, in pseudo_json
    return json.loads(data.encode().decode("utf-8-sig"))
  File "/usr/local/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.10/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 1 column 21 (char 20)

### Your device model

RT-AC86U

### Firmware type

Stock

### Firmware version

3.0.0.4.386_48260

### Integration version with the issue

0.17.4

### Method of the integration installation

HACS

### What version and type of Home Assistant installation do you use

2023.1.4

**Comment by merlin-zaraza** [comment]
Reboot of the router resolved this issue

**Comment by Vaskivskyi** [comment]
Hello,

Apparently, the API on your device has partially stuck and reported some incorrect data.

That's good, it was resolved with a reboot.

I'll use your logs to improve the integration to avoid such issues in the future. Thanks!

**Comment by Vaskivskyi** [comment]
With the next release the backend library will be handling JSON errors by itself and users will not see the errors that you saw in your log. I am closing the issue. Thanks for your report!
