### ISSUE TITLE
Integration stopped working

### ISSUE THREAD

**Issue by Din-BH** [Vaskivskyi/ha-asusrouter#471]
### The problem

I have had the AsusWRT extension working for more than a year, but decided to give AsusRouter a try due to the more sophisticated connection mechanism and options.

I had the setup running very well for several days - however, shortly after last update to 0.17.4 I noticed after a while that the network up/down and other sensors stopped updating - turns out that the whole integration is not functioning anymore.

Rebooting does not help. I have not tried re-install. Included some debug logs, which hopefully would make you able to at least find some angle to this.

Also tried to edit the config from the integrations menu, as logging seemed to indicate to me that it was using ssl, even if that option was not set in settings. But attempt to change things just created more errors in log..

### Your device model

RT-AC86U

### Firmware type

Merlin

### Firmware version

3.0.0.4.386.9_0

### Integration version with the issue

0.17.4

### Method of the integration installation

HACS

### What version and type of Home Assistant installation do you use

2023.1.4

### Is there anything useful in the logs?

```txt
2023-01-15 10:30:02.070 DEBUG (MainThread) [asusrouter.connection] No certificate provided. Using trusted
2023-01-15 10:30:04.969 DEBUG (MainThread) [asusrouter.connection] Login successful on port 80: {'Model_Name': 'RT-AC86U', 'AiHOMEAPILevel': '21', 'Httpd_AiHome_Ver': '0'}
2023-01-15 10:30:04.970 DEBUG (MainThread) [asusrouter.asusrouter] Identifying the device
2023-01-15 10:30:56.687 WARNING (MainThread) [homeassistant.bootstrap] Waiting on integrations to complete setup: asusrouter

  [repeated 6 times, roughly once per minute]

2023-01-15 10:37:39.890 WARNING (MainThread) [homeassistant.config_entries] Config entry 'xx.xx.xx.xx' for asusrouter integration not ready yet: argument of type 'coroutine' is not iterable; Retrying in background
2023-01-15 10:37:41.082 DEBUG (MainThread) [asusrouter.connection] No certificate provided. Using trusted
2023-01-15 10:37:52.290 DEBUG (MainThread) [asusrouter.connection] Login successful on port 80: {'Model_Name': 'RT-AC86U', 'AiHOMEAPILevel': '21', 'Httpd_AiHome_Ver': '0'}
2023-01-15 10:37:52.291 DEBUG (MainThread) [asusrouter.asusrouter] Identifying the device

  [repeated 7 times, roughly every 9 minutes]

2023-01-15 11:45:23.324 DEBUG (MainThread) [asusrouter.asusrouter] Identity collected
2023-01-15 11:45:23.469 DEBUG (MainThread) [asusrouter.connection] Login successful on port 80: {'Model_Name': 'RT-AC86U', 'AiHOMEAPILevel': '21', 'Httpd_AiHome_Ver': '0'}
2023-01-15 11:50:23.498 ERROR (MainThread) [custom_components.asusrouter.router] Error connecting to 'xx.xx.xx.xx' for device update: None
2023-01-15 11:52:43.572 DEBUG (MainThread) [asusrouter.connection] Connection refused. Endpoint: appGet.cgi. Payload: hook=get_clientlist().
2023-01-15 11:52:43.573 DEBUG (MainThread) [asusrouter.connection] Reconnecting
2023-01-15 11:52:48.597 DEBUG (MainThread) [asusrouter.connection] Login successful on port 80: {'Model_Name': 'RT-AC86U', 'AiHOMEAPILevel': '21', 'Httpd_AiHome_Ver': '0'}
2023-01-15 11:52:53.641 DEBUG (MainThread) [asusrouter.connection] Login successful on port 80: {'Model_Name': 'RT-AC86U', 'AiHOMEAPILevel': '21', 'Httpd_AiHome_Ver': '0'}
2023-01-15 12:00:03.917 DEBUG (MainThread) [asusrouter.connection] Connection refused. Endpoint: appGet.cgi. Payload: hook=cpu_usage(appobj);memory_usage(appobj);netdev(appobj);wanlink_state(appobj);.
2023-01-15 12:00:03.919 DEBUG (MainThread) [asusrouter.connection] Reconnecting
2023-01-15 12:00:08.951 DEBUG (MainThread) [asusrouter.connection] Login successful on port 80: {'Model_Name': 'RT-AC86U', 'AiHOMEAPILevel': '21', 'Httpd_AiHome_Ver': '0'}
2023-01-15 12:00:13.986 DEBUG (MainThread) [asusrouter.connection] Login successful on port 80: {'Model_Name': 'RT-AC86U', 'AiHOMEAPILevel': '21', 'Httpd_AiHome_Ver': '0'}
2023-01-15 12:00:14.035 DEBUG (MainThread) [asusrouter.asusrouter] Error flag found
2023-01-15 12:05:15.493 ERROR (MainThread) [custom_components.asusrouter.router] Error fetching gwlan data: None
2023-01-15 12:07:24.306 DEBUG (MainThread) [asusrouter.connection] Connection refused. Endpoint: appGet.cgi. Payload: hook=cpu_usage(appobj);memory_usage(appobj);netdev(appobj);wanlink_state(appobj);.
2023-01-15 12:07:24.308 DEBUG (MainThread) [asusrouter.connection] Reconnecting
2023-01-15 12:07:29.332 DEBUG (MainThread) [asusrouter.connection] Login successful on port 80: {'Model_Name': 'RT-AC86U', 'AiHOMEAPILevel': '21', 'Httpd_AiHome_Ver': '0'}
2023-01-15 12:07:34.364 DEBUG (MainThread) [asusrouter.connection] Login successful on port 80: {'Model_Name': 'RT-AC86U', 'AiHOMEAPILevel': '21', 'Httpd_AiHome_Ver': '0'}
2023-01-15 12:07:34.405 DEBUG (MainThread) [asusrouter.asusrouter] Error flag found
2023-01-15 12:12:34.496 ERROR (MainThread) [custom_components.asusrouter.router] Error fetching parental_control data: None
2023-01-15 12:14:44.705 DEBUG (MainThread) [asusrouter.connection] Connection refused. Endpoint: ajax_ethernet_ports.asp. Payload: .
2023-01-15 12:14:44.706 DEBUG (MainThread) [asusrouter.connection] Reconnecting
2023-01-15 12:14:49.739 DEBUG (MainThread) [asusrouter.connection] Login successful on port 80: {'Model_Name': 'RT-AC86U', 'AiHOMEAPILevel': '21', 'Httpd_AiHome_Ver': '0'}
2023-01-15 12:14:54.783 DEBUG (MainThread) [asusrouter.connection] Login successful on port 80: {'Model_Name': 'RT-AC86U', 'AiHOMEAPILevel': '21', 'Httpd_AiHome_Ver': '0'}
2023-01-15 12:14:55.258 DEBUG (MainThread) [asusrouter.asusrouter] Error flag found
2023-01-15 12:19:55.507 ERROR (MainThread) [custom_components.asusrouter.router] Error fetching wlan data: None
2023-01-15 12:19:56.262 ERROR (MainThread) [homeassistant.components.switch] Error adding entities for domain switch with platform asusrouter
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 438, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 631, in _async_add_entity
    original_icon=entity.icon,
  File "/config/custom_components/asusrouter/entity.py", line 133, in icon
    if self.is_on:
  File "/config/custom_components/asusrouter/entity.py", line 126, in is_on
    return self.coordinator.data.get(self.entity_description.key)
AttributeError: 'NoneType' object has no attribute 'get'
2023-01-15 12:19:56.736 ERROR (MainThread) [homeassistant.components.switch] Error while setting up asusrouter platform for switch
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 297, in _async_setup_platform
    await asyncio.gather(*pending)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 438, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 631, in _async_add_entity
    original_icon=entity.icon,
  File "/config/custom_components/asusrouter/entity.py", line 133, in icon
    if self.is_on:
  File "/config/custom_components/asusrouter/entity.py", line 126, in is_on
    return self.coordinator.data.get(self.entity_description.key)
AttributeError: 'NoneType' object has no attribute 'get'
2023-01-15 12:20:05.558 WARNING (MainThread) [homeassistant.components.binary_sensor] Setup of binary_sensor platform asusrouter is taking over 10 seconds.
2023-01-15 12:20:05.584 WARNING (MainThread) [homeassistant.components.light] Setup of light platform asusrouter is taking over 10 seconds.
2023-01-15 12:20:05.595 WARNING (MainThread) [homeassistant.components.sensor] Setup of sensor platform asusrouter is taking over 10 seconds.
2023-01-15 12:20:05.611 WARNING (MainThread) [homeassistant.components.update] Setup of update platform asusrouter is taking over 10 seconds.
2023-01-15 12:22:05.080 DEBUG (MainThread) [asusrouter.connection] Connection refused. Endpoint: appGet.cgi. Payload: hook=nvram_get(led_val);.
2023-01-15 12:22:05.082 DEBUG (MainThread) [asusrouter.connection] Reconnecting
2023-01-15 12:22:05.084 DEBUG (MainThread) [asusrouter.connection] Connection refused. Endpoint: appGet.cgi. Payload: hook=cpu_usage(appobj);memory_usage(appobj);netdev(appobj);wanlink_state(appobj);.
2023-01-15 12:22:05.085 DEBUG (MainThread) [asusrouter.connection] Reconnecting
2023-01-15 12:22:05.100 DEBUG (MainThread) [asusrouter.connection] Connection refused. Endpoint: ajax_ethernet_ports.asp. Payload: .
2023-01-15 12:22:05.101 DEBUG (MainThread) [asusrouter.connection] Reconnecting
2023-01-15 12:22:05.103 DEBUG (MainThread) [asusrouter.connection] Connection refused. Endpoint: appGet.cgi. Payload: hook=nvram_get(wl0.1_akm);nvram_get(wl0.1_ap_isolate);nvram_get(wl0.1_auth);nvram_get(wl0.1_auth_mode);nvram_get(wl0.1_auth_mode_x);nvram_get(wl0.1_bridge);nvram_get(wl0.1_bss_enabled);nvram_get(wl0.1_bss_maxassoc);nvram_get(wl0.1_bw_dl);nvram_get(wl0.1_bw_enabled);nvram_get(wl0.1_bw_ul);nvram_get(wl0.1_closed);nvram_get(wl0.1_crypto);nvram_get(wl0.1_expire);nvram_get(wl0.1_expire_tmp);nvram_get(wl0.1_gn_wbl_enable);nvram_get(wl0.1_gn_wbl_rule);nvram_get(wl0.1_gn_wbl_type);nvram_get(wl0.1_hwaddr);nvram_get(wl0.1_ifname);nvram_get(wl0.1_infra);nvram_get(wl0.1_key);nvram_get(wl0.1_key1);nvram_get(wl0.1_key2);nvram_get(wl0.1_key3);nvram_get(wl0.1_key4);nvram_get(wl0.1_lanaccess);nvram_get(wl0.1_maclist);nvram_get(wl0.1_macmode);nvram_get(wl0.1_maxassoc);nvram_get(wl0.1_mbss);nvram_get(wl0.1_mfp);nvram_get(wl0.1_mode);nvram_get(wl0.1_net_reauth);nvram_get(wl0.1_preauth);nvram_get(wl0.1_radio);nvram_get(wl0.1_radius_ipaddr);nvram_get(wl0.1_radius_key);nvram_get(wl0.1_radius_port);nvram_get(wl0.1_sae_anti_clog_threshold);nvram_get(wl0.1_sae_groups);nvram_get(wl0.1_sae_sync);nvram_get(wl0.1_ssid);nvram_get(wl0.1_sta_retry_time);nvram_get(wl0.1_sync_node);nvram_get(wl0.1_unit);nvram_get(wl0.1_wep);nvram_get(wl0.1_wep_x);nvram_get(wl0.1_wfi_enable);nvram_get(wl0.1_wfi_pinmode);nvram_get(wl0.1_wme);nvram_get(wl0.1_wme_bss_disable);nvram_get(wl0.1_wpa_gtk_rekey);nvram_get(wl0.1_wpa_psk);nvram_get(wl0.1_wps_mode);nvram_get(wl0.2_akm);nvram_get(wl0.2_ap_isolate);nvram_get(wl0.2_auth);nvram_get(wl0.2_auth_mode);nvram_get(wl0.2_auth_mode_x);nvram_get(wl0.2_bridge);nvram_get(wl0.2_bss_enabled);nvram_get(wl0.2_bss_maxassoc);nvram_get(wl0.2_bw_dl);nvram_get(wl0.2_bw_enabled);nvram_get(wl0.2_bw_ul);nvram_get(wl0.2_closed);nvram_get(wl0.2_crypto);nvram_get(wl0.2_expire);nvram_get(wl0.2_expire_tmp);nvram_get(wl0.2_gn_wbl_enable);nvram_get(wl0.2_gn_wbl_rule);nvram_get(wl0.2_gn_wbl_type);nvram_get(wl0.2_hwaddr);nvram_get(wl0.2_ifname);nvram_get(wl0.2_infra);nvram_get(wl0.2_key);nvram_get(wl0.2_key1);nvram_get(wl0.2_key2);nvram_get(wl0.2_key3);nvram_get(wl0.2_key4);nvram_get(wl0.2_lanaccess);nvram_get(wl0.2_maclist);nvram_get(wl0.2_macmode);nvram_get(wl0.2_maxassoc);nvram_get(wl0.2_mbss);nvram_get(wl0.2_mfp);nvram_get(wl0.2_mode);nvram_get(wl0.2_net_reauth);nvram_get(wl0.2_preauth);nvram_get(wl0.2_radio);nvram_get(wl0.2_radius_ipaddr);nvram_get(wl0.2_radius_key);nvram_get(wl0.2_radius_port);nvram_get(wl0.2_sae_anti_clog_threshold);nvram_get(wl0.2_sae_groups);nvram_get(wl0.2_sae_sync);nvram_get(wl0.2_ssid);nvram_get(wl0.2_sta_retry_time);nvram_get(wl0.2_sync_node);nvram_get(wl0.2_unit);nvram_get(wl0.2_wep);nvram_get(wl0.2_wep_x);nvram_get(wl0.2_wfi_enable);nvram_get(wl0.2_wfi_pinmode);nvram_get(wl0.2_wme);nvram_get(wl0.2_wme_bss_disable);nvram_get(wl0.2_wpa_gtk_rekey);nvram_get(wl0.2_wpa_psk);nvram_get(wl0.2_wps_mode);nvram_get(wl0.3_akm);nvram_get(wl0.3_ap_isolate);nvram_get(wl0.3_auth);nvram_get(wl0.3_auth_mode);nvram_get(wl0.3_auth_mode_x);nvram_get(wl0.3_bridge);nvram_get(wl0.3_bss_enabled);nvram_get(wl0.3_bss_maxassoc);nvram_get(wl0.3_bw_dl);nvram_get(wl0.3_bw_enabled);nvram_get(wl0.3_bw_ul);nvram_get(wl0.3_closed);nvram_get(wl0.3_crypto);nvram_get(wl0.3_expire);nvram_get(wl0.3_expire_tmp);nvram_get(wl0.3_gn_wbl_enable);nvram_get(wl0.3_gn_wbl_rule);nvram_get(wl0.3_gn_wbl_type);nvram_get(wl0.3_hwaddr);nvram_get(wl0.3_ifname);nvram_get(wl0.3_infra);nvram_get(wl0.3_key);nvram_get(wl0.3_key1);nvram_get(wl0.3_key2);nvram_get(wl0.3_key3);nvram_get(wl0.3_key4);nvram_get(wl0.3_lanaccess);nvram_get(wl0.3_maclist);nvram_get(wl0.3_macmode);nvram_get(wl0.3_maxassoc);nvram_get(wl0.3_mbss);nvram_get(wl0.3_mfp);nvram_get(wl0.3_mode);nvram_get(wl0.3_net_reauth);nvram_get(wl0.3_preauth);nvram_get(wl0.3_radio);nvram_get(wl0.3_radius_ipaddr);nvram_get(wl0.3_radius_key);nvram_get(wl0.3_radius_port);nvram_get(wl0.3_sae_anti_clog_threshold);nvram_get(wl0.3_sae_groups);nvram_get(wl0.3_sae_sync);nvram_get(wl0.3_ssid);nvram_get(wl0.3_sta_retry_time);nvram_get(wl0.3_sync_node);nvram_get(wl0.3_unit);nvram_get(wl0.3_wep);nvram_get(wl0.3_wep_x);nvram_get(wl0.3_wfi_enable);nvram_get(wl0.3_wfi_pinmode);nvram_get(wl0.3_wme);nvram_get(wl0.3_wme_bss_disable);nvram_get(wl0.3_wpa_gtk_rekey);nvram_get(wl0.3_wpa_psk);nvram_get(wl0.3_wps_mode);nvram_get(wl1.1_akm);nvram_get(wl1.1_ap_isolate);nvram_get(wl1.1_auth);nvram_get(wl1.1_auth_mode);nvram_get(wl1.1_auth_mode_x);nvram_get(wl1.1_bridge);nvram_get(wl1.1_bss_enabled);nvram_get(wl1.1_bss_maxassoc);nvram_get(wl1.1_bw_dl);nvram_get(wl1.1_bw_enabled);nvram_get(wl1.1_bw_ul);nvram_get(wl1.1_closed);nvram_get(wl1.1_crypto);nvram_get(wl1.1_expire);nvram_get(wl1.1_expire_tmp);nvram_get(wl1.1_gn_wbl_enable);nvram_get(wl1.1_gn_wbl_rule);nvram_get(wl1.1_gn_wbl_type);nvram_get(wl1.1_hwaddr);nvram_get(wl1.1_ifname);nvram_get(wl1.1_infra);nvram_get(wl1.1_key);nvram_get(wl1.1_key1);nvram_get(wl1.1_key2);nvram_get(wl1.1_key3);nvram_get(wl1.1_key4);nvram_get(wl1.1_lanaccess);nvram_get(wl1.1_maclist);nvram_get(wl1.1_macmode);nvram_get(wl1.1_maxassoc);nvram_get(wl1.1_mbss);nvram_get(wl1.1_mfp);nvram_get(wl1.1_mode);nvram_get(wl1.1_net_reauth);nvram_get(wl1.1_preauth);nvram_get(wl1.1_radio);nvram_get(wl1.1_radius_ipaddr);nvram_get(wl1.1_radius_key);nvram_get(wl1.1_radius_port);nvram_get(wl1.1_sae_anti_clog_threshold);nvram_get(wl1.1_sae_groups);nvram_get(wl1.1_sae_sync);nvram_get(wl1.1_ssid);nvram_get(wl1.1_sta_retry_time);nvram_get(wl1.1_sync_node);nvram_get(wl1.1_unit);nvram_get(wl1.1_wep);nvram_get(wl1.1_wep_x);nvram_get(wl1.1_wfi_enable);nvram_get(wl1.1_wfi_pinmode);nvram_get(wl1.1_wme);nvram_get(wl1.1_wme_bss_disable);nvram_get(wl1.1_wpa_gtk_rekey);nvram_get(wl1.1_wpa_psk);nvram_get(wl1.1_wps_mode);nvram_get(wl1.2_akm);nvram_get(wl1.2_ap_isolate);nvram_get(wl1.2_auth);nvram_get(wl1.2_auth_mode);nvram_get(wl1.2_auth_mode_x);nvram_get(wl1.2_bridge);nvram_get(wl1.2_bss_enabled);nvram_get(wl1.2_bss_maxassoc);nvram_get(wl1.2_bw_dl);nvram_get(wl1.2_bw_enabled);nvram_get(wl1.2_bw_ul);nvram_get(wl1.2_closed);nvram_get(wl1.2_crypto);nvram_get(wl1.2_expire);nvram_get(wl1.2_expire_tmp);nvram_get(wl1.2_gn_wbl_enable);nvram_get(wl1.2_gn_wbl_rule);nvram_get(wl1.2_gn_wbl_type);nvram_get(wl1.2_hwaddr);nvram_get(wl1.2_ifname);nvram_get(wl1.2_infra);nvram_get(wl1.2_key);nvram_get(wl1.2_key1);nvram_get(wl1.2_key2);nvram_get(wl1.2_key3);nvram_get(wl1.2_key4);nvram_get(wl1.2_lanaccess);nvram_get(wl1.2_maclist);nvram_get(wl1.2_macmode);nvram_get(wl1.2_maxassoc);nvram_get(wl1.2_mbss);nvram_get(wl1.2_mfp);nvram_get(wl1.2_mode);nvram_get(wl1.2_net_reauth);nvram_get(wl1.2_preauth);nvram_get(wl1.2_radio);nvram_get(wl1.2_radius_ipaddr);nvram_get(wl1.2_radius_key);nvram_get(wl1.2_radius_port);nvram_get(wl1.2_sae_anti_clog_threshold);nvram_get(wl1.2_sae_groups);nvram_get(wl1.2_sae_sync);nvram_get(wl1.2_ssid);nvram_get(wl1.2_sta_retry_time);nvram_get(wl1.2_sync_node);nvram_get(wl1.2_unit);nvram_get(wl1.2_wep);nvram_get(wl1.2_wep_x);nvram_get(wl1.2_wfi_enable);nvram_get(wl1.2_wfi_pinmode);nvram_get(wl1.2_wme);nvram_get(wl1.2_wme_bss_disable);nvram_get(wl1.2_wpa_gtk_rekey);nvram_get(wl1.2_wpa_psk);nvram_get(wl1.2_wps_mode);nvram_get(wl1.3_akm);nvram_get(wl1.3_ap_isolate);nvram_get(wl1.3_auth);nvram_get(wl1.3_auth_mode);nvram_get(wl1.3_auth_mode_x);nvram_get(wl1.3_bridge);nvram_get(wl1.3_bss_enabled);nvram_get(wl1.3_bss_maxassoc);nvram_get(wl1.3_bw_dl);nvram_get(wl1.3_bw_enabled);nvram_get(wl1.3_bw_ul);nvram_get(wl1.3_closed);nvram_get(wl1.3_crypto);nvram_get(wl1.3_expire);nvram_get(wl1.3_expire_tmp);nvram_get(wl1.3_gn_wbl_enable);nvram_get(wl1.3_gn_wbl_rule);nvram_get(wl1.3_gn_wbl_type);nvram_get(wl1.3_hwaddr);nvram_get(wl1.3_ifname);nvram_get(wl1.3_infra);nvram_get(wl1.3_key);nvram_get(wl1.3_key1);nvram_get(wl1.3_key2);nvram_get(wl1.3_key3);nvram_get(wl1.3_key4);nvram_get(wl1.3_lanaccess);nvram_get(wl1.3_maclist);nvram_get(wl1.3_macmode);nvram_get(wl1.3_maxassoc);nvram_get(wl1.3_mbss);nvram_get(wl1.3_mfp);nvram_get(wl1.3_mode);nvram_get(wl1.3_net_reauth);nvram_get(wl1.3_preauth);nvram_get(wl1.3_radio);nvram_get(wl1.3_radius_ipaddr);nvram_get(wl1.3_radius_key);nvram_get(wl1.3_radius_port);nvram_get(wl1.3_sae_anti_clog_threshold);nvram_get(wl1.3_sae_groups);nvram_get(wl1.3_sae_sync);nvram_get(wl1.3_ssid);nvram_get(wl1.3_sta_retry_time);nvram_get(wl1.3_sync_node);nvram_get(wl1.3_unit);nvram_get(wl1.3_wep);nvram_get(wl1.3_wep_x);nvram_get(wl1.3_wfi_enable);nvram_get(wl1.3_wfi_pinmode);nvram_get(wl1.3_wme);nvram_get(wl1.3_wme_bss_disable);nvram_get(wl1.3_wpa_gtk_rekey);nvram_get(wl1.3_wpa_psk);nvram_get(wl1.3_wps_mode);.
2023-01-15 12:22:05.103 DEBUG (MainThread) [asusrouter.connection] Reconnecting
2023-01-15 12:22:05.107 DEBUG (MainThread) [asusrouter.connection] Connection refused. Endpoint: appGet.cgi. Payload: hook=nvram_get(MULTIFILTER_ALL);nvram_get(MULTIFILTER_ENABLE);nvram_get(MULTIFILTER_DEVICENAME);nvram_get(MULTIFILTER_MAC);nvram_get(MULTIFILTER_MACFILTER_DAYTIME_V2);.
2023-01-15 12:22:05.108 DEBUG (MainThread) [asusrouter.connection] Reconnecting
2023-01-15 12:22:05.110 DEBUG (MainThread) [asusrouter.connection] Connection refused. Endpoint: appGet.cgi. Payload: hook=nvram_get(wl0_auth_mode_x);nvram_get(wl0_bw);nvram_get(wl0_channel);nvram_get(wl0_chanspec);nvram_get(wl0_closed);nvram_get(wl0_country_code);nvram_get(wl0_crypto);nvram_get(wl0_gmode_check);nvram_get(wl0_maclist_x);nvram_get(wl0_macmode);nvram_get(wl0_mbo_enable);nvram_get(wl0_mfp);nvram_get(wl0_nmode_x);nvram_get(wl0_optimizexbox_ckb);nvram_get(wl0_radio);nvram_get(wl0_radius_ipaddr);nvram_get(wl0_radius_key);nvram_get(wl0_radius_port);nvram_get(wl0_ssid);nvram_get(wl0_wpa_gtk_rekey);nvram_get(wl0_wpa_psk);nvram_get(wl1_auth_mode_x);nvram_get(wl1_bw);nvram_get(wl1_channel);nvram_get(wl1_chanspec);nvram_get(wl1_closed);nvram_get(wl1_country_code);nvram_get(wl1_crypto);nvram_get(wl1_gmode_check);nvram_get(wl1_maclist_x);nvram_get(wl1_macmode);nvram_get(wl1_mbo_enable);nvram_get(wl1_mfp);nvram_get(wl1_nmode_x);nvram_get(wl1_optimizexbox_ckb);nvram_get(wl1_radio);nvram_get(wl1_radius_ipaddr);nvram_get(wl1_radius_key);nvram_get(wl1_radius_port);nvram_get(wl1_ssid);nvram_get(wl1_wpa_gtk_rekey);nvram_get(wl1_wpa_psk);.
2023-01-15 12:22:05.110 DEBUG (MainThread) [asusrouter.connection] Reconnecting
2023-01-15 12:22:05.113 DEBUG (MainThread) [asusrouter.connection] Connection refused. Endpoint: apply.cgi. Payload: {'action_mode': 'firmware_check'}.
2023-01-15 12:22:05.113 DEBUG (MainThread) [asusrouter.connection] Reconnecting
2023-01-15 12:22:05.124 DEBUG (MainThread) [asusrouter.connection] Reconnecting
2023-01-15 12:22:05.126 DEBUG (MainThread) [asusrouter.connection] Reconnecting
2023-01-15 12:22:05.129 DEBUG (MainThread) [asusrouter.connection] Reconnecting
2023-01-15 12:22:05.164 DEBUG (MainThread) [asusrouter.connection] Login successful on port 80: {'Model_Name': 'RT-AC86U', 'AiHOMEAPILevel': '21', 'Httpd_AiHome_Ver': '0'}
2023-01-15 12:27:05.495 ERROR (MainThread) [custom_components.asusrouter.router] Error connecting to 'xx.xx.xx.xx' for device update: None
2023-01-15 12:27:10.556 ERROR (MainThread) [custom_components.asusrouter.router] Error fetching ports data: None
2023-01-15 12:27:10.588 ERROR (MainThread) [custom_components.asusrouter.router] Error fetching wan data: None
2023-01-15 12:27:10.597 ERROR (MainThread) [custom_components.asusrouter.light] LED control has returned an exception: None
2023-01-15 12:27:10.613 ERROR (MainThread) [custom_components.asusrouter.router] Error fetching firmware data: None
2023-01-15 13:12:43.237 DEBUG (MainThread) [asusrouter.connection] Certificate won't be checked
2023-01-15 13:12:43.261 DEBUG (MainThread) [asusrouter.connection] Login successful on port 80: {'Model_Name': 'RT-AC86U', 'AiHOMEAPILevel': '21', 'Httpd_AiHome_Ver': '0'}
2023-01-15 13:12:43.262 DEBUG (MainThread) [asusrouter.asusrouter] Identifying the device
2023-01-15 13:14:30.659 DEBUG (MainThread) [asusrouter.connection] No certificate provided. Using trusted
2023-01-15 13:14:45.164 DEBUG (MainThread) [asusrouter.connection] Certificate won't be checked
2023-01-15 13:15:30.679 ERROR (MainThread) [custom_components.asusrouter.config_flow] Unknown error of type '<class 'homeassistant.exceptions.ConfigEntryNotReady'>' during connection to xx.xx.xx.xx: ('Cannot connect to host xx.xx.xx.xx:80 ssl:True [None]', None)
2023-01-15 13:15:45.186 ERROR (MainThread) [custom_components.asusrouter.config_flow] Unknown error of type '<class 'homeassistant.exceptions.ConfigEntryNotReady'>' during connection to xx.xx.xx.xx: ('Cannot connect to host xx.xx.xx.xx:80 ssl:False [None]', None)
2023-01-15 13:20:07.730 ERROR (MainThread) [custom_components.asusrouter.config_flow] Unknown error of type '<class 'homeassistant.exceptions.ConfigEntryNotReady'>' during connection to xx.xx.xx.xx: argument of type 'coroutine' is not iterable
```

### Diagnostics information

[config_entry-asusrouter-517f04fb0955f9f2144af11ca816278f.json.txt](https://github.com/Vaskivskyi/ha-asusrouter/files/10427842/config_entry-asusrouter-517f04fb0955f9f2144af11ca816278f.json.txt)

**Comment by Vaskivskyi** [comment]
Hey, sorry for the problems you are experiencing. Do you remember, on which the last AsusRouter version you had everything worked well?

**Comment by Din-BH** [comment]
0.17.1 I had installed for a few days working fine. Then I upgraded first merlin to latest and then a few days later AsusRouter.

**Comment by Din-BH** [comment]
Update; This seems to be an issue with the new Merlin release - potentially in conjunction with AsusRouter use of the httpd interface. The httpd of Merlin FW in teh router was responding ULTRASLOW. SSH into the router worked without issues, which is why AsusWRT integration worked but not the AsusRouter integration. Restarting the httpd did not work, but router restart remedied the situation at least for now. Will keep monitoring.
