### ISSUE TITLE
[Bug] Error loading the integration after 0.21.1 update

### ISSUE THREAD

**Issue by contrasenda** [Vaskivskyi/ha-asusrouter#558]
### The problem

Hi!

After updating asusrouter integration to version 0.21.1 and restarting Home Assistant, the integration doesn't get loaded. Rebooted HA again with the same problem. Going back to 0.21.0 the integration loads and works normally.

### Your device model

RT-AX92U

### Firmware type

Stock

### Firmware version

3.0.0.4.388_22525

### Integration version with the issue

0.21.1

### Method of the integration installation

HACS

### What version and type of Home Assistant installation do you use

2023.2.5

### Is there anything useful in the logs?

```txt
2023-02-26 15:23:24.546 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry 192.168.1.1 for asusrouter
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/asusrouter/asusrouter.py", line 311, in async_identify
    data = item.method(raw[item.value]) if item.method else raw[item.value]
KeyError: 'serial_no'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 382, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/asusrouter/__init__.py", line 26, in async_setup_entry
    await router.setup()
  File "/config/custom_components/asusrouter/router.py", line 632, in setup
    await self.bridge.async_connect()
  File "/config/custom_components/asusrouter/bridge.py", line 176, in async_connect
    await self.api.async_connect()
  File "/usr/local/lib/python3.10/site-packages/asusrouter/asusrouter.py", line 255, in async_connect
    await self.async_identify()
  File "/usr/local/lib/python3.10/site-packages/asusrouter/asusrouter.py", line 320, in async_identify
    raise AsusRouterIdentityError(
asusrouter.error.AsusRouterIdentityError: ("Cannot obtain identity from the device 192.168.1.1. Exception summary'serial_no'", None)
```

**Comment by Vaskivskyi** [comment]
Hello, @contrasenda,

Sorry to hear, you are experiencing issues with AsusRouter

This is a bit strange, that this part fails for your device only on 0.21.1, but not 0.21.0. The only change between these 2 versions is a dependency upgrade for network communications to be compatible with HA 2023.3. And not related anyhow to the data processing from the device

Let me think about it a bit. I will let you know what to try

**Comment by contrasenda** [comment]
Thanks, let me know if you need any debug logs. 
One thing I just remembered is that, after updating to 0.21.0, HA discovered my router as a new device with a name like 192.168.1.1_1040. I discarded the notification as I didn't want to lose all my tracking devices names. O:-)

**Comment by mariwing** [comment]
I can add to this that after you added auto discovery my router is found on each reboot of Hass, even if it configured already. After the latest update to 0.21.1 the integration no longer works. I have the following in the logs:

Logger: custom_components.asusrouter.config_flow
Source: custom_components/asusrouter/config_flow.py:634
Integration: AsusRouter (documentation, issues)
First occurred: 14:33:53 (1 occurrences)
Last logged: 14:33:53

Unknown error of type '<class 'asusrouter.error.AsusRouterResponseError'>' during connection to `192.168.0.1`: ('Unknown error code `10`, please report it', None)

If I try to add the device (even though it is already added) this shows up:
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/discovery_flow.py", line 71, in _async_start
    await gather_with_concurrency(
  File "/usr/src/homeassistant/homeassistant/util/async_.py", line 201, in gather_with_concurrency
    return await gather(
  File "/usr/src/homeassistant/homeassistant/util/async_.py", line 199, in sem_task
    return await task
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 798, in async_init
    flow, result = await task
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 826, in _async_init
    result = await self._async_handle_step(flow, flow.init_step, data)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 335, in _async_handle_step
    result: FlowResult = await getattr(flow, method)(user_input)
  File "/config/custom_components/asusrouter/config_flow.py", line 548, in async_step_ssdp
    discovery_info.upnp[ssdp.ATTR_UPNP_MODEL_DESCRIPTION]
KeyError: 'modelDescription'

**Comment by contrasenda** [comment]
After updating this morning HA to 2023.3.1 the asusrouter integration version 0.21.0 stopped working. I updated asusrouter to latest 0.21.1 and now everything is working perfectly. :-)
 For my part, this bug report can be closed.
