### ISSUE TITLE
[Bug] Asus integration not loading after Home Assistant core update to 2023.8.1

### ISSUE THREAD

**Issue by BeHappy2021** [Vaskivskyi/ha-asusrouter#609]
### The problem

Just updated core to 2023.8.1 and got a message that the integration cannot be loaded. No devices are accessible and no options to reload or anything.

### Your device model

RT-A68U

### Firmware type

Stock

### Firmware version

3.0.0.4.386_51665

### Integration version with the issue

0.22.0

### Method of the integration installation

HACS

### What version and type of Home Assistant installation do you use

Operating System 10.4,  Core 2023.8.1

### Is there anything useful in the logs?

```txt
Two log entries:

This error originated from a custom integration.

Logger: homeassistant.loader
Source: custom_components/asusrouter/const.py:8
Integration: AsusRouter (documentation, issues)
First occurred: 09:04:23 (1 occurrences)
Last logged: 09:04:23

Unexpected exception importing component custom_components.asusrouter
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 813, in get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/config/custom_components/asusrouter/__init__.py", line 11, in <module>
    from .const import ASUSROUTER, DOMAIN, PLATFORMS, STOP_LISTENER
  File "/config/custom_components/asusrouter/const.py", line 8, in <module>
    from asusrouter.util import converters
  File "/usr/local/lib/python3.11/site-packages/asusrouter/__init__.py", line 30, in <module>
    from .connection import Connection
  File "/usr/local/lib/python3.11/site-packages/asusrouter/connection.py", line 26, in <module>
    from asusrouter.const import (
SyntaxError: source code string cannot contain null bytes

Logger: homeassistant.setup
Source: loader.py:821
First occurred: 09:04:23 (1 occurrences)
Last logged: 09:04:23

Setup failed for custom integration asusrouter: Unable to import component: Exception importing custom_components.asusrouter
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 813, in get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/config/custom_components/asusrouter/__init__.py", line 11, in <module>
    from .const import ASUSROUTER, DOMAIN, PLATFORMS, STOP_LISTENER
  File "/config/custom_components/asusrouter/const.py", line 8, in <module>
    from asusrouter.util import converters
  File "/usr/local/lib/python3.11/site-packages/asusrouter/__init__.py", line 30, in <module>
    from .connection import Connection
  File "/usr/local/lib/python3.11/site-packages/asusrouter/connection.py", line 26, in <module>
    from asusrouter.const import (
SyntaxError: source code string cannot contain null bytes

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 215, in _async_setup_component
    component = integration.get_component()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 821, in get_component
    raise ImportError(f"Exception importing {self.pkg_path}") from err
ImportError: Exception importing custom_components.asusrouter
```

### Additional information

Only fix I've found is to roll back to Core 2023.8.0

**Comment by smarthomefamilyverrips** [comment]
Same here, but it not started directly after the update, at me started after a restart of the system today

This error originated from a custom integration.

Logger: homeassistant.config_entries
Source: custom_components/asusrouter/bridge.py:173
Integration: AsusRouter (documentation, issues)
First occurred: 14:03:35 (1 occurrences)
Last logged: 14:03:35

Error setting up entry 192.168.0.1 for asusrouter
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 388, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/asusrouter/__init__.py", line 26, in async_setup_entry
    await router.setup()
  File "/config/custom_components/asusrouter/router.py", line 632, in setup
    await self.bridge.async_connect()
  File "/config/custom_components/asusrouter/bridge.py", line 173, in async_connect
    await self.api.async_connect()
  File "/usr/local/lib/python3.11/site-packages/asusrouter/asusrouter.py", line 253, in async_connect
    raise ex
  File "/usr/local/lib/python3.11/site-packages/asusrouter/asusrouter.py", line 251, in async_connect
    await self.connection.async_connect()
  File "/usr/local/lib/python3.11/site-packages/asusrouter/connection.py", line 298, in async_connect
    response = await self.async_request(
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/asusrouter/connection.py", line 210, in async_request
    raise AsusRouterResponseError(
asusrouter.error.AsusRouterResponseError: ('Unknown error code `10`, please report it', None)

@Vaskivskyi can you have a look 🙏

**Comment by mihsu81** [comment]
Works fine in my case on RT-AX88U Pro, RT-AX88U and TUF-AX5400 with  HA 2023.8.1 and 0.22.0.

**Comment by smarthomefamilyverrips** [comment]
> Works fine in my case on RT-AX88U Pro, RT-AX88U and TUF-AX5400 with HA 2023.8.1 and 0.22.0.

After 1.5 hour waiting and several times trying to reload integration it also started to work at me again... as said above I not had the error directly after update to 2023.8.1  and did do several restarts since this update all was fine till today... so seems to me it suddenly randomly can give the error and also as sudden will work again after time passes... so to me this still feels like a bug @Vaskivskyi 

@BeHappy2021 maybe you can try again update to HA 2023.8.1 and wait a bit in case integration fail to start again, and try some reloads of integration after some time passes

**Comment by BeHappy2021** [comment]
Just updated to 2023.8.1 again and everything has gone fine. Weird! I've restarted a couple of times and all is still fine and nothing in the error logs. Thanks for the extra info @mihsu81 and @smarthomefamilyverrips. I'll close this now.

**Comment by Vaskivskyi** [comment]
Hello and sorry for the late reply.

@BeHappy2021, the original issue seems to be connected to Python itself and not to the integration or background library. I have tried to reproduce it in several different environments but didn't manage to get the same error. In any case, I'm glad that the issue was solved by itself by just upgrading HA once more. In any case, if it will happen again, please open a new issue and we'll try to troubleshoot it and find the reason.

@smarthomefamilyverrips, I'm sorry for the issue you experienced. I was quite sure, that this error code was already added to the integration. But it was not yet. The error code reports that your device is requiring a captcha to be solved to log in. Might be, there were too many login attempts in a short period of time. In any case, it's not possible to solve this request from the integration side. The only two ways - to wait or to reboot the device. I'll make sure, the error code will be added to the integration as soon as possible, so next time the log will help users to understand the problem.

**Comment by smarthomefamilyverrips** [comment]
> Hello and sorry for the late reply.
> 
> @BeHappy2021, the original issue seems to be connected to Python itself and not to the integration or background library. I have tried to reproduce it in several different environments but didn't manage to get the same error. In any case, I'm glad that the issue was solved by itself by just upgrading HA once more. In any case, if it will happen again, please open a new issue and we'll try to troubleshoot it and find the reason.
> 
> @smarthomefamilyverrips, I'm sorry for the issue you experienced. I was quite sure, that this error code was already added to the integration. But it was not yet. The error code reports that your device is requiring a captcha to be solved to log in. Might be, there were too many login attempts in a short period of time. In any case, it's not possible to solve this request from the integration side. The only two ways - to wait or to reboot the device. I'll make sure, the error code will be added to the integration as soon as possible, so next time the log will help users to understand the problem.

@Vaskivskyi no problem for the delay am happy to see you are still maintaining this great integration, seeing you be less active as normal kind had me worried you abandon the integration.

Thank you also for the explanation,  at this moment all works fine again also after still doing 1 or 2 more restart 👍

**Comment by BeHappy2021** [comment]
No problem @Vaskivskyi and thanks for your work in making this and keeping it maintained.

**Comment by poudenes** [comment]
Here it works fine:

Home Assistant 2023.8.1
Supervisor 2023.08.1
Operating System 10.4
Frontend 20230802.0 - latest

Router:

GT-AX11000
by ASUSTek
Firmware: 3.0.0.4.388.2_2 (merlin)
