### ISSUE TITLE
[Bug] Inegration not starts after update to 0.23.0b0

### ISSUE THREAD

**Issue by smarthomefamilyverrips** [Vaskivskyi/ha-asusrouter#641]
### The problem

After update to latest version 0.23.0b0 integration fails to start, rollback to 0.22.0 makes all work as expected again

Logger: homeassistant.config_entries
Source: config_entries.py:399
First occurred: 20:56:47 (3 occurrences)
Last logged: 20:58:05

Error setting up entry 192.168.0.1 for asusrouter
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 399, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/asusrouter/__init__.py", line 26, in async_setup_entry
    await router.setup()
  File "/config/custom_components/asusrouter/router.py", line 352, in setup
    await self._init_sensor_coordinators()
  File "/config/custom_components/asusrouter/router.py", line 563, in _init_sensor_coordinators
    available_sensors = await self.bridge.async_get_available_sensors()
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/asusrouter/bridge.py", line 224, in async_get_available_sensors
    SENSORS: await self._get_sensors_sysinfo(),
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/asusrouter/bridge.py", line 494, in _get_sensors_sysinfo
    return await self._get_sensors(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/asusrouter/bridge.py", line 441, in _get_sensors
    process(data) if process is not None else self._process_sensors(data)
    ^^^^^^^^^^^^^
  File "/config/custom_components/asusrouter/bridge.py", line 564, in _process_sensors_sysinfo
    if sensor_type in raw:
       ^^^^^^^^^^^^^^^^^^
TypeError: argument of type 'NoneType' is not iterable

### Your device model

Zenwifi Pro XT12

### Firmware type

Stock

### Firmware version

3.0.0.4.388_22127

### Integration version with the issue

0.23.0b0

### Method of the integration installation

HACS

### What version and type of Home Assistant installation do you use

Core 2023.10.5

### Is there anything useful in the logs?

```txt
Logger: homeassistant.config_entries
Source: config_entries.py:399
First occurred: 20:56:47 (3 occurrences)
Last logged: 20:58:05

Error setting up entry 192.168.0.1 for asusrouter
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 399, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/asusrouter/__init__.py", line 26, in async_setup_entry
    await router.setup()
  File "/config/custom_components/asusrouter/router.py", line 352, in setup
    await self._init_sensor_coordinators()
  File "/config/custom_components/asusrouter/router.py", line 563, in _init_sensor_coordinators
    available_sensors = await self.bridge.async_get_available_sensors()
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/asusrouter/bridge.py", line 224, in async_get_available_sensors
    SENSORS: await self._get_sensors_sysinfo(),
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/asusrouter/bridge.py", line 494, in _get_sensors_sysinfo
    return await self._get_sensors(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/asusrouter/bridge.py", line 441, in _get_sensors
    process(data) if process is not None else self._process_sensors(data)
    ^^^^^^^^^^^^^
  File "/config/custom_components/asusrouter/bridge.py", line 564, in _process_sensors_sysinfo
    if sensor_type in raw:
       ^^^^^^^^^^^^^^^^^^
TypeError: argument of type 'NoneType' is not iterable
```

**Comment by Vaskivskyi** [comment]
Hello. Sorry for the issue you are experiencing. I am already working on it

**Comment by smarthomefamilyverrips** [comment]
No problem happy to try and help find issues! 😊

**Comment by Vaskivskyi** [comment]
@smarthomefamilyverrips, please, check whether it works now with `0.23.0b1`

**Comment by smarthomefamilyverrips** [comment]
@Vaskivskyi now all seems to work as expected 👍🏻

**Comment by Vaskivskyi** [comment]
Great! 👍🏻
