### ISSUE TITLE
Error on each server startup - Unexpected error fetching port_forwarding data: 'rules'

### ISSUE THREAD

**Issue by billraff** [Vaskivskyi/ha-asusrouter#651]
### The problem

On each server restart getting an error with latest release. Debug log gathered and attached.

### Your device model

RT-AX95Q

### Firmware type

Stock

### Firmware version

3.0.0.4.388.23285_g5068da5

### Integration version with the issue

0.22

### Method of the integration installation

HACS

### What version and type of Home Assistant installation do you use

Frontend 20231005.0 - latest

### Is there anything useful in the logs?

```txt
2023-10-30 09:24:46.288 ERROR (MainThread) [custom_components.asusrouter.router] Unexpected error fetching port_forwarding data: 'rules'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 290, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 246, in _async_update_data
    return await self.update_method()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/asusrouter/bridge.py", line 322, in _get_data_port_forwarding
    return await self._get_data(
           ^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/asusrouter/bridge.py", line 263, in _get_data
    return process(raw)
           ^^^^^^^^^^^^
  File "/config/custom_components/asusrouter/bridge.py", line 392, in _process_data_port_forwarding
    for rule in raw["rules"]:
                ~~~^^^^^^^^^
KeyError: 'rules'
```

### Diagnostics information

[home-assistant_asusrouter_2023-10-30T14-26-44.951Z.log](https://github.com/Vaskivskyi/ha-asusrouter/files/13216786/home-assistant_asusrouter_2023-10-30T14-26-44.951Z.log)

**Comment by Vaskivskyi** [comment]
@billraff, Do you have any port forwarding rules set on your device?

This will be fixed as soon as possible

**Comment by billraff** [comment]
Have no Port forwarding Rules. That's why I thought it was funny to see that particular exception.

**Comment by Vaskivskyi** [comment]
Sorry for this. The fix is ready and will be available in the next beta release (either later today or tomorrow)
