### ISSUE TITLE
[Bug] 0.23 Setup Failed

### ISSUE THREAD

**Issue by Jozziej** [Vaskivskyi/ha-asusrouter#662]
### The problem

After upgrading to HA 2023.11.0 the Asus integration fails to setup after working for years.

### Your device model

RT-AC87u

### Firmware type

Merlin

### Firmware version

384.13_10

### Integration version with the issue

0.23

### Method of the integration installation

HACS

### What version and type of Home Assistant installation do you use

Core 2023.11.0

### Is there anything useful in the logs?

```txt
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 402, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/asusrouter/__init__.py", line 26, in async_setup_entry
    await router.setup()
  File "/config/custom_components/asusrouter/router.py", line 345, in setup
    await self.update_clients()
  File "/config/custom_components/asusrouter/router.py", line 485, in update_clients
    self.update_latest_connected()
  File "/config/custom_components/asusrouter/router.py", line 530, in update_latest_connected
    self._latest_connected = new_list[-1].get(CONNECTED)
                             ~~~~~~~~^^^^
IndexError: list index out of range
```

**Comment by Vaskivskyi** [comment]
Hello. Sorry for the issue you are experiencing. Please, update to the `0.23.1` which is already available in HACS. It should solve your issue

**Comment by Jozziej** [comment]
Ah weird, I just see the new version now. Fixed
