### ISSUE TITLE
[Bug]  RT-AC87U don't work

### ISSUE THREAD

**Issue by raffaelevall** [Vaskivskyi/ha-asusrouter#665]
### The problem

Hi, 
after update to the 0.23.1 the integration can't connect to the router

### Your device model

RT-AC87U

### Firmware type

Merlin

### Firmware version

3.0.0.4 (build 384.13)

### Integration version with the issue

0.23.1

### Method of the integration installation

HACS

### What version and type of Home Assistant installation do you use

Core 2023.11.0

### Is there anything useful in the logs?

```txt
Logger: homeassistant.config_entries
Source: config_entries.py:402
First occurred: 12:29:27 (2 occurrences)
Last logged: 12:49:39

Error setting up entry 192.168.1.1 for asusrouter
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 402, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/asusrouter/__init__.py", line 26, in async_setup_entry
    await router.setup()
  File "/config/custom_components/asusrouter/router.py", line 352, in setup
    await self._init_sensor_coordinators()
  File "/config/custom_components/asusrouter/router.py", line 616, in _init_sensor_coordinators
    available_sensors = await self.bridge.async_get_available_sensors()
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/asusrouter/bridge.py", line 228, in async_get_available_sensors
    SENSORS: await self._get_sensors_temperature(),
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/asusrouter/bridge.py", line 507, in _get_sensors_temperature
    return await self._get_sensors(AsusData.TEMPERATURE, sensor_type=TEMPERATURE)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/asusrouter/bridge.py", line 440, in _get_sensors
    data = await self.api.async_get_data(datatype)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/asusrouter/asusrouter.py", line 451, in async_get_data
    data = await self.async_api_load(endpoint, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/asusrouter/asusrouter.py", line 276, in async_api_load
    result = read(endpoint, content)
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/asusrouter/modules/endpoint/__init__.py", line 78, in read
    return submodule.read(content)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/asusrouter/modules/endpoint/temperature.py", line 33, in read
    temperature[Wlan.FREQ_5G2] = variables["curr_coreTmp_52_raw"]
                                 ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'curr_coreTmp_52_raw'
```

**Comment by Vaskivskyi** [comment]
Hello. Sorry for the issue you are experiencing. It will be fixed later today and a new release will be available in HACS (`< 12 h` from now)

**Comment by raffaelevall** [comment]
> Ciao. Ci scusiamo per il problema che stai riscontrando. Il problema verrà risolto più tardi oggi e una nuova versione sarà disponibile in HACS ( `< 12 h`da ora)

Many tks @Vaskivskyi

**Comment by Vaskivskyi** [comment]
Hey, please check `0.23.2` which should be already available in HACS

**Comment by raffaelevall** [comment]
> Hey, please check `0.23.2` which should be already available in HACS

Hi my friend, don't works for me

```
Logger: homeassistant.config_entries
Source: config_entries.py:402
First occurred: 08:05:28 (4 occurrences)
Last logged: 08:23:24

Error setting up entry 192.168.1.1 for asusrouter
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 402, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/asusrouter/__init__.py", line 26, in async_setup_entry
    await router.setup()
  File "/config/custom_components/asusrouter/router.py", line 352, in setup
    await self._init_sensor_coordinators()
  File "/config/custom_components/asusrouter/router.py", line 616, in _init_sensor_coordinators
    available_sensors = await self.bridge.async_get_available_sensors()
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/asusrouter/bridge.py", line 228, in async_get_available_sensors
    SENSORS: await self._get_sensors_temperature(),
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/asusrouter/bridge.py", line 507, in _get_sensors_temperature
    return await self._get_sensors(AsusData.TEMPERATURE, sensor_type=TEMPERATURE)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/asusrouter/bridge.py", line 440, in _get_sensors
    data = await self.api.async_get_data(datatype)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/asusrouter/asusrouter.py", line 451, in async_get_data
    data = await self.async_api_load(endpoint, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/asusrouter/asusrouter.py", line 276, in async_api_load
    result = read(endpoint, content)
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/asusrouter/modules/endpoint/__init__.py", line 78, in read
    return submodule.read(content)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/asusrouter/modules/endpoint/temperature.py", line 49, in read
    temperature[key] = value.replace("&deg;C", "")
                       ^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'replace'
```

**Comment by Vaskivskyi** [comment]
Ow, hell...

I have just arranged access to one older Asus model before 386 FW for a short test today. I hope, this one would help to solve all the issues with 384 and below versions in the current version

**Comment by Vaskivskyi** [comment]
Can you please check `0.23.3`? I have managed to test it on RT-AC6U with 380.70, so I hope it will work for you as well

**Comment by raffaelevall** [comment]
> Can you please check `0.23.3`? I have managed to test it on RT-AC6U with 380.70, so I hope it will work for you as well

Works for my RT-AC87U, tks a lot

**Comment by Vaskivskyi** [comment]
Great! 👍🏻
