### ISSUE TITLE
[Bug] Access Error flooding the logs

### ISSUE THREAD

**Issue by zSprawl** [Vaskivskyi/ha-asusrouter#675]
### The problem

After updating from 0.22.x to 0.23.x, I've been having this error in the morning when I wake up. It fills my log file with hundreds of thousands of errors all saying the same thing. I merely reload the integration to fix it, since it appears to be some login error.

`This error originated from a custom integration.

Logger: homeassistant
Source: custom_components/asusrouter/bridge.py:261
Integration: AsusRouter (documentation, issues)
First occurred: 9:15:35 AM (28 occurrences)
Last logged: 9:29:08 AM

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/asusrouter/asusrouter.py", line 256, in async_api_load
    status, _, content = await self.async_api_query(endpoint, request)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/asusrouter/asusrouter.py", line 242, in async_api_query
    return await self._connection.async_query(endpoint, payload)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/asusrouter/connection.py", line 249, in async_query
    return await self._send_request(endpoint, payload, headers)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/asusrouter/connection.py", line 228, in _send_request
    raise ex
  File "/usr/local/lib/python3.11/site-packages/asusrouter/connection.py", line 217, in _send_request
    return handle_access_error(
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/asusrouter/modules/endpoint/error.py", line 60, in handle_access_error
    raise AsusRouterAccessError(
asusrouter.error.AsusRouterAccessError: ('Access error', <AccessError.AUTHORIZATION: 2>, {}, None)`

### Your device model

RT-AX95Q

### Firmware type

Merlin

### Firmware version

3.0.0.4.388.2_2_0-gnuton1

### Integration version with the issue

0.23.x

### Method of the integration installation

HACS

### What version and type of Home Assistant installation do you use

Supervisor 2023.10.1

**Comment by Vaskivskyi** [comment]
Hello. Sorry to hear you are experiencing such an issue with the integration. The `authorization` error means a request was sent without the integration being actually "logged in" to the device.

Please, let me know whether you are using an SSL connection. Also, enable debug logging for the integration and backend library. At the beginning of the log you should see something like this:

```
2023-11-05 08:13:44.069 DEBUG (MainThread) [custom_components.asusrouter] Setting up entry
2023-11-05 08:13:44.069 DEBUG (MainThread) [asusrouter.asusrouter] Initializing a new interface to `192.168.XXX.XXX`
2023-11-05 08:13:44.069 DEBUG (MainThread) [asusrouter.connection] Initializing a new connection to `192.168.XXX.XXX`
2023-11-05 08:13:44.069 DEBUG (MainThread) [asusrouter.connection] Using session `<aiohttp.client.ClientSession object at 0x7fb071bd4790>`
2023-11-05 08:13:44.070 DEBUG (MainThread) [asusrouter.connection] Using `https` and port `8443`
2023-11-05 08:13:44.070 DEBUG (MainThread) [custom_components.asusrouter.router] Setting up router
2023-11-05 08:13:44.070 DEBUG (MainThread) [custom_components.asusrouter.bridge] Connecting to the API
2023-11-05 08:13:44.070 DEBUG (MainThread) [asusrouter.asusrouter] Triggered method async_connect
2023-11-05 08:13:44.070 DEBUG (MainThread) [asusrouter.connection] Initializing connection to 192.168.XXX.XXX
2023-11-05 08:13:44.070 DEBUG (MainThread) [asusrouter.connection] Requesting authorization
2023-11-05 08:13:45.117 DEBUG (MainThread) [asusrouter.connection] Received authorization response
2023-11-05 08:13:45.117 DEBUG (MainThread) [asusrouter.connection] Connected to 192.168.XXX.XXX
2023-11-05 08:13:45.117 DEBUG (MainThread) [asusrouter.asusrouter] Triggered method async_get_identity
2023-11-05 08:13:45.117 DEBUG (MainThread) [asusrouter.modules.identity] Collecting device identity
```

We need to find out whether it does not connect anymore, or the connection drops during the operation

**Comment by pergolafabio** [comment]
seeing same issue here, my log file was 5 GB big!

**Comment by pergolafabio** [comment]
I never saw this issue before, i think it started happening since 23.x release, not sure witch one

**Comment by pergolafabio** [comment]
Now i know what was causing my other issue:

https://github.com/home-assistant/core/issues/103390

**Comment by pergolafabio** [comment]
I have now enabled debug on the component, i dont use the SSL option to connect
I want to give you the diagnostics, but when downloading it, i receive this error:

```
2023-11-05 13:26:55.974 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_protocol.py", line 433, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 85, in security_filter_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 227, in forwarded_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 80, in ban_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 236, in auth_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/headers.py", line 31, in headers_middleware
    response = await handler(request)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 148, in handle
    result = await handler(request, **request.match_info)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/diagnostics/__init__.py", line 249, in get
    data = await info.config_entry_diagnostics(hass, config_entry)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/asusrouter/diagnostics.py", line 85, in async_get_config_entry_diagnostics
    "ip_address": device.ip,
                  ^^^^^^^^^
AttributeError: 'ARClient' object has no attribute 'ip'
```

**Comment by Vaskivskyi** [comment]
@pergolafabio,

please, let me know your device model and FW version.

Also, try to reconfigure the integration using an SSL connection (it should be also enabled in the router settings)

**Comment by pergolafabio** [comment]
I'm using an RT-AC88u, with 2 aimesh nodes RT-AC86U

Main router is using merlin, the aimesh nodes are running stock, all latest firmware:

![image](https://github.com/Vaskivskyi/ha-asusrouter/assets/43251136/99fdeb86-190d-4842-b344-8bd27a2af7f6)

I have now debug enabled, once the issue occurs again, i post the logs...


![image](https://github.com/Vaskivskyi/ha-asusrouter/assets/43251136/3f915eca-2137-46f3-88d6-cea4c317254b)

**Comment by pergolafabio** [comment]
I also noted a new light (led) entity, is that new? i never noticed it before, maybe related? i didnt saw anything in release notes for a new light?

**Comment by Vaskivskyi** [comment]
The LED entity was available before for users with `control mode` enabled. Since the `control mode` option in configurations was removed from the latest version, the LED entity is now available to everyone

**Comment by pergolafabio** [comment]
ok, happened again, here it started flooding the log....
```

2023-11-05 13:25:52.159 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration asusrouter which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-11-05 13:26:19.443 DEBUG (MainThread) [custom_components.asusrouter] Setting up entry
2023-11-05 13:26:19.444 DEBUG (MainThread) [asusrouter.asusrouter] Initializing a new interface to `192.168.0.1`
2023-11-05 13:26:19.445 DEBUG (MainThread) [asusrouter.connection] Initializing a new connection to `192.168.0.1`
2023-11-05 13:26:19.445 DEBUG (MainThread) [asusrouter.connection] Using session `<aiohttp.client.ClientSession object at 0x7ffb68cca710>`
2023-11-05 13:26:19.445 DEBUG (MainThread) [asusrouter.connection] Using `http` and port `80`
2023-11-05 13:26:19.445 DEBUG (MainThread) [custom_components.asusrouter.router] Setting up router
2023-11-05 13:26:19.445 DEBUG (MainThread) [custom_components.asusrouter.bridge] Connecting to the API
2023-11-05 13:26:19.445 DEBUG (MainThread) [asusrouter.asusrouter] Triggered method async_connect
2023-11-05 13:26:19.445 DEBUG (MainThread) [asusrouter.connection] Initializing connection to 192.168.0.1
2023-11-05 13:26:19.445 DEBUG (MainThread) [asusrouter.connection] Requesting authorization
2023-11-05 13:26:19.520 WARNING (MainThread) [py.warnings] /config/custom_components/kostal/sensor.py:245: RuntimeWarning: coroutine 'PikoData.async_info_update' was never awaited
  self.async_info_update()

2023-11-05 13:26:19.624 DEBUG (MainThread) [asusrouter.connection] Received authorization response
2023-11-05 13:26:19.624 DEBUG (MainThread) [asusrouter.connection] Connected to 192.168.0.1
2023-11-05 13:26:19.625 DEBUG (MainThread) [asusrouter.asusrouter] Triggered method async_get_identity
2023-11-05 13:26:19.625 DEBUG (MainThread) [asusrouter.modules.identity] Collecting device identity
2023-11-05 13:26:19.625 DEBUG (MainThread) [asusrouter.asusrouter] Triggered method async_api_hook: nvram_get(serial_no);nvram_get(label_mac);nvram_get(lan_hwaddr);nvram_get(wan_hwaddr);nvram_get(productid);nvram_get(firmver);nvram_get(buildno);nvram_get(extendno);nvram_get(rc_support);nvram_get(ss_support);nvram_get(led_val);
2023-11-05 13:26:19.625 DEBUG (MainThread) [asusrouter.asusrouter] Triggered method async_api_load: Endpoint.HOOK
2023-11-05 13:26:19.626 DEBUG (MainThread) [asusrouter.asusrouter] Triggered method async_api_query: Endpoint.HOOK | hook=nvram_get(serial_no);nvram_get(label_mac);nvram_get(lan_hwaddr);nvram_get(wan_hwaddr);nvram_get(productid);nvram_get(firmver);nvram_get(buildno);nvram_get(extendno);nvram_get(rc_support);nvram_get(ss_support);nvram_get(led_val);
2023-11-05 13:26:19.626 DEBUG (MainThread) [asusrouter.connection] Sending request to 192.168.0.1
2023-11-05 13:26:20.161 DEBUG (MainThread) [asusrouter.asusrouter] Response 200 received from Endpoint.HOOK
2023-11-05 13:26:20.161 DEBUG (MainThread) [asusrouter.modules.endpoint] Reading data from endpoint Endpoint.HOOK
2023-11-05 13:26:20.167 DEBUG (MainThread) [asusrouter.modules.identity] Identity collected
2023-11-05 13:26:20.167 DEBUG (MainThread) [asusrouter.modules.identity] Identity read
2023-11-05 13:26:20.167 DEBUG (MainThread) [asusrouter.asusrouter] Triggered method async_api_query: Endpoint.DEVICEMAP | None
2023-11-05 13:26:20.168 DEBUG (MainThread) [asusrouter.connection] Sending request to 192.168.0.1
2023-11-05 13:26:21.079 DEBUG (MainThread) [asusrouter.asusrouter] Triggered method async_api_query: Endpoint.ETHERNET_PORTS | None
2023-11-05 13:26:21.079 DEBUG (MainThread) [asusrouter.connection] Sending request to 192.168.0.1
2023-11-05 13:26:21.282 DEBUG (MainThread) [asusrouter.asusrouter] Triggered method async_api_query: Endpoint.FIRMWARE | None
2023-11-05 13:26:21.282 DEBUG (MainThread) [asusrouter.connection] Sending request to 192.168.0.1
2023-11-05 13:26:21.567 DEBUG (MainThread) [asusrouter.asusrouter] Triggered method async_api_query: Endpoint.HOOK | None
2023-11-05 13:26:21.567 DEBUG (MainThread) [asusrouter.connection] Sending request to 192.168.0.1
2023-11-05 13:26:21.919 DEBUG (MainThread) [asusrouter.asusrouter] Triggered method async_api_query: Endpoint.NETWORKMAPD | None
2023-11-05 13:26:21.919 DEBUG (MainThread) [asusrouter.connection] Sending request to 192.168.0.1
2023-11-05 13:26:21.957 DEBUG (MainThread) [asusrouter.asusrouter] Triggered method async_api_query: Endpoint.ONBOARDING | None
2023-11-05 13:26:21.957 DEBUG (MainThread) [asusrouter.connection] Sending request to 192.168.0.1
2023-11-05 13:26:22.014 DEBUG (MainThread) [asusrouter.asusrouter] Triggered method async_api_query: Endpoint.PORT_STATUS | 
2023-11-05 13:26:22.014 DEBUG (MainThread) [asusrouter.connection] Sending request to 192.168.0.1
2023-11-05 13:26:22.088 DEBUG (MainThread) [asusrouter.asusrouter] Triggered method async_api_query: Endpoint.RGB | None
2023-11-05 13:26:22.088 DEBUG (MainThread) [asusrouter.connection] Sending request to 192.168.0.1
2023-11-05 13:26:22.122 DEBUG (MainThread) [asusrouter.asusrouter] Triggered method async_api_query: Endpoint.STATE | None
2023-11-05 13:26:22.122 DEBUG (MainThread) [asusrouter.connection] Sending request to 192.168.0.1
2023-11-05 13:26:22.346 DEBUG (MainThread) [asusrouter.asusrouter] Triggered method async_api_query: Endpoint.SYSINFO | None
2023-11-05 13:26:22.346 DEBUG (MainThread) [asusrouter.connection] Sending request to 192.168.0.1
2023-11-05 13:26:22.454 DEBUG (MainThread) [asusrouter.asusrouter] Triggered method async_api_query: Endpoint.TEMPERATURE | None
2023-11-05 13:26:22.454 DEBUG (MainThread) [asusrouter.connection] Sending request to 192.168.0.1
2023-11-05 13:26:22.475 DEBUG (MainThread) [asusrouter.asusrouter] Triggered method async_api_query: Endpoint.UPDATE_CLIENTS | None
2023-11-05 13:26:22.475 DEBUG (MainThread) [asusrouter.connection] Sending request to 192.168.0.1
2023-11-05 13:26:23.036 DEBUG (MainThread) [asusrouter.asusrouter] Triggered method async_api_query: Endpoint.VPN | None
2023-11-05 13:26:23.037 DEBUG (MainThread) [asusrouter.connection] Sending request to 192.168.0.1
2023-11-05 13:26:25.959 WARNING (MainThread) [homeassistant.helpers.entity] Updating state for calendar.quintens_vanessa_gmail_com (<class 'homeassistant.components.google.calendar.GoogleCalendarEntity'>) took 0.842 seconds. Please create a bug report at https://github.com/home-assistant/core/issues?q=is%3Aopen+is%3Aissue+label%3A%22integration%3A+google%22
2023-11-05 13:26:26.241 DEBUG (MainThread) [asusrouter.modules.identity] Endpoints checked
2023-11-05 13:26:26.241 DEBUG (MainThread) [asusrouter.asusrouter] Triggered method async_get_identity
2023-11-05 13:26:26.241 DEBUG (MainThread) [custom_components.asusrouter.router] Bridge connected
2023-11-05 13:26:26.242 DEBUG (MainThread) [custom_components.asusrouter.router] Updating AiMesh status for '192.168.0.1'
2023-11-05 13:26:26.242 DEBUG (MainThread) [asusrouter.asusrouter] Triggered method _check_state
2023-11-05 13:26:26.242 DEBUG (MainThread) [asusrouter.asusrouter] Triggered method _where_to_get_data
2023-11-05 13:26:26.242 DEBUG (MainThread) [asusrouter.asusrouter] Endpoints to check: [<Endpoint.ONBOARDING: 'ajax_onboarding.asp'>]
2023-11-05 13:26:26.242 DEBUG (MainThread) [asusrouter.asusrouter] Triggered method async_api_load: Endpoint.ONBOARDING
2023-11-05 13:26:26.243 DEBUG (MainThread) [asusrouter.asusrouter] Triggered method async_api_query: Endpoint.ONBOARDING | 
2023-11-05 13:26:26.243 DEBUG (MainThread) [asusrouter.connection] Sending request to 192.168.0.1
2023-11-05 13:26:26.339 DEBUG (MainThread) [asusrouter.asusrouter] Response 200 received from Endpoint.ONBOARDING
2023-11-05 13:26:26.339 DEBUG (MainThread) [asusrouter.modules.endpoint] Reading data from endpoint Endpoint.ONBOARDING
2023-11-05 13:26:26.341 DEBUG (MainThread) [asusrouter.modules.endpoint] Processing data from endpoint Endpoint.ONBOARDING
2023-11-05 13:26:26.341 DEBUG (MainThread) [asusrouter.asusrouter] Triggered method _transform_data for `AsusData.AIMESH`
2023-11-05 13:26:26.342 DEBUG (MainThread) [asusrouter.asusrouter] Triggered method _transform_data for `AsusData.CLIENTS`
2023-11-05 13:26:26.342 DEBUG (MainThread) [asusrouter.asusrouter] Transforming clients data
2023-11-05 13:26:26.343 DEBUG (MainThread) [asusrouter.asusrouter] Triggered method _check_flags
2023-11-05 13:26:26.343 DEBUG (MainThread) [asusrouter.asusrouter] Returning data for `AsusData.AIMESH` with object type `<class 'dict'>`
2023-11-05 13:26:26.344 DEBUG (MainThread) [custom_components.asusrouter.router] Firing event `asusrouter_node_connected` with arguments: {'mac': '3c:7c:3f:60:c6:48', 'ip': '192.168.0.1', 'alias': 'Home', 'model': 'RT-AC88U', 'type': 'router', 'connected': True}
2023-11-05 13:26:26.344 DEBUG (MainThread) [custom_components.asusrouter.router] Firing event `asusrouter_node_connected` with arguments: {'mac': '0c:9d:92:46:4e:a0', 'ip': '192.168.0.3', 'alias': 'Third Floor', 'model': 'RT-AC86U', 'type': 'router', 'connected': True}
2023-11-05 13:26:26.344 DEBUG (MainThread) [custom_components.asusrouter.router] Firing event `asusrouter_node_connected` with arguments: {'mac': '24:4b:fe:be:7c:10', 'ip': '192.168.0.2', 'alias': 'Second Floor', 'model': 'RT-AC86U', 'type': 'router', 'connected': True}
2023-11-05 13:26:26.344 DEBUG (MainThread) [custom_components.asusrouter.router] Firing event `asusrouter_node_connected` with arguments: {'mac': '04:d4:c4:c7:d4:00', 'ip': None, 'alias': None, 'model': None, 'type': None, 'connected': False}
2023-11-05 13:26:26.344 DEBUG (MainThread) [custom_components.asusrouter.router] Device tracking is disabled
2023-11-05 13:26:26.344 DEBUG (MainThread) [custom_components.asusrouter.router] Updating AsusRouter device list for '192.168.0.1'
2023-11-05 13:26:26.344 DEBUG (MainThread) [asusrouter.asusrouter] Triggered method _check_state
2023-11-05 13:26:26.344 DEBUG (MainThread) [asusrouter.asusrouter] Triggered method _where_to_get_data
2023-11-05 13:26:26.344 DEBUG (MainThread) [asusrouter.asusrouter] Endpoints to check: [<Endpoint.ONBOARDING: 'ajax_onboarding.asp'>, <Endpoint.UPDATE_CLIENTS: 'update_clients.asp'>]
2023-11-05 13:26:26.344 DEBUG (MainThread) [asusrouter.asusrouter] Triggered method async_api_load: Endpoint.ONBOARDING
2023-11-05 13:26:26.344 DEBUG (MainThread) [asusrouter.asusrouter] Triggered method async_api_query: Endpoint.ONBOARDING | 
2023-11-05 13:26:26.344 DEBUG (MainThread) [asusrouter.connection] Sending request to 192.168.0.1
2023-11-05 13:26:26.386 DEBUG (MainThread) [asusrouter.asusrouter] Response 200 received from Endpoint.ONBOARDING
2023-11-05 13:26:26.386 DEBUG (MainThread) [asusrouter.modules.endpoint] Reading data from endpoint Endpoint.ONBOARDING
2023-11-05 13:26:26.387 DEBUG (MainThread) [asusrouter.modules.endpoint] Processing data from endpoint Endpoint.ONBOARDING
2023-11-05 13:26:26.387 DEBUG (MainThread) [asusrouter.asusrouter] Triggered method async_api_load: Endpoint.UPDATE_CLIENTS
2023-11-05 13:26:26.387 DEBUG (MainThread) [asusrouter.asusrouter] Triggered method async_api_query: Endpoint.UPDATE_CLIENTS | 
2023-11-05 13:26:26.387 DEBUG (MainThread) [asusrouter.connection] Sending request to 192.168.0.1
2023-11-05 13:26:26.691 DEBUG (MainThread) [asusrouter.asusrouter] Response 200 received from Endpoint.UPDATE_CLIENTS
2023-11-05 13:26:26.691 DEBUG (MainThread) [asusrouter.modules.endpoint] Reading data from endpoint Endpoint.UPDATE_CLIENTS
2023-11-05 13:26:26.693 DEBUG (MainThread) [asusrouter.modules.endpoint.update_clients] Reading modern update clients data
2023-11-05 13:26:26.695 DEBUG (MainThread) [asusrouter.modules.endpoint] Processing data from endpoint Endpoint.UPDATE_CLIENTS
2023-11-05 13:26:26.697 DEBUG (MainThread) [asusrouter.asusrouter] Triggered method _transform_data for `AsusData.AIMESH`
2023-11-05 13:26:26.697 DEBUG (MainThread) [asusrouter.asusrouter] Triggered method _transform_data for `AsusData.CLIENTS`
2023-11-05 13:26:26.697 DEBUG (MainThread) [asusrouter.asusrouter] Transforming clients data
2023-11-05 13:26:26.702 DEBUG (MainThread) [asusrouter.asusrouter] Triggered method _check_flags
2023-11-05 13:26:26.702 DEBUG (MainThread) [asusrouter.asusrouter] Returning data for `AsusData.CLIENTS` with object type `<class 'dict'>`
..............


2023-11-05 15:30:51.858 DEBUG (MainThread) [asusrouter.asusrouter] Triggered method async_connect
2023-11-05 15:30:51.858 DEBUG (MainThread) [asusrouter.connection] Already connected to 192.168.0.1
2023-11-05 15:30:51.858 DEBUG (MainThread) [asusrouter.asusrouter] Triggered method async_get_identity
2023-11-05 15:30:51.858 DEBUG (MainThread) [asusrouter.asusrouter] Triggered method async_api_load: Endpoint.ONBOARDING
2023-11-05 15:30:51.858 DEBUG (MainThread) [asusrouter.asusrouter] Triggered method async_api_query: Endpoint.ONBOARDING | 
2023-11-05 15:30:51.858 DEBUG (MainThread) [asusrouter.connection] Sending request to 192.168.0.1
2023-11-05 15:30:51.865 DEBUG (MainThread) [asusrouter.modules.endpoint.error] Access error message: {'error_status': '2', 'last_time_lock_warning': '0'}
2023-11-05 15:30:51.865 DEBUG (MainThread) [asusrouter.asusrouter] Triggered method async_connect
2023-11-05 15:30:51.865 DEBUG (MainThread) [asusrouter.connection] Already connected to 192.168.0.1
2023-11-05 15:30:51.866 DEBUG (MainThread) [asusrouter.asusrouter] Triggered method async_get_identity
2023-11-05 15:30:51.866 DEBUG (MainThread) [asusrouter.asusrouter] Triggered method async_api_load: Endpoint.ONBOARDING
2023-11-05 15:30:51.866 DEBUG (MainThread) [asusrouter.asusrouter] Triggered method async_api_query: Endpoint.ONBOARDING | 
2023-11-05 15:30:51.866 DEBUG (MainThread) [asusrouter.connection] Sending request to 192.168.0.1
2023-11-05 15:30:51.872 DEBUG (MainThread) [asusrouter.modules.endpoint.error] Access error message: {'error_status': '2', 'last_time_lock_warning': '0'}
2023-11-05 15:30:51.873 DEBUG (MainThread) [asusrouter.asusrouter] Triggered method async_connect
2023-11-05 15:30:51.873 DEBUG (MainThread) [asusrouter.connection] Already connected to 192.168.0.1
2023-11-05 15:30:51.873 DEBUG (MainThread) [asusrouter.asusrouter] Triggered method async_get_identity
2023-11-05 15:30:51.873 DEBUG (MainThread) [asusrouter.asusrouter] Triggered method async_api_load: Endpoint.ONBOARDING
2023-11-05 15:30:51.873 DEBUG (MainThread) [asusrouter.asusrouter] Triggered method async_api_query: Endpoint.ONBOARDING | 
2023-11-05 15:30:51.873 DEBUG (MainThread) [asusrouter.connection] Sending request to 192.168.0.1
2023-11-05 15:30:51.880 DEBUG (MainThread) [asusrouter.modules.endpoint.error] Access error message: {'error_status': '2', 'last_time_lock_warning': '0'}
2023-11-05 15:30:51.880 DEBUG (MainThread) [asusrouter.asusrouter] Triggered method async_connect
2023-11-05 15:30:51.880 DEBUG (MainThread) [asusrouter.connection] Already connected to 192.168.0.1
2023-11-05 15:30:51.880 DEBUG (MainThread) [asusrouter.asusrouter] Triggered method async_get_identity
2023-11-05 15:30:51.880 DEBUG (MainThread) [asusrouter.asusrouter] Triggered method async_api_load: Endpoint.ONBOARDING
2023-11-05 15:30:51.880 DEBUG (MainThread) [asusrouter.asusrouter] Triggered method async_api_query: Endpoint.ONBOARDING | 
2023-11-05 15:30:51.880 DEBUG (MainThread) [asusrouter.connection] Sending request to 192.168.0.1
2023-11-05 15:30:51.884 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/asusrouter/asusrouter.py", line 256, in async_api_load
    status, _, content = await self.async_api_query(endpoint, request)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/asusrouter/asusrouter.py", line 242, in async_api_query
    return await self._connection.async_query(endpoint, payload)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/asusrouter/connection.py", line 249, in async_query
    return await self._send_request(endpoint, payload, headers)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/asusrouter/connection.py", line 228, in _send_request
    raise ex
  File "/usr/local/lib/python3.11/site-packages/asusrouter/connection.py", line 217, in _send_request
    return handle_access_error(
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/asusrouter/modules/endpoint/error.py", line 60, in handle_access_error
    raise AsusRouterAccessError(
asusrouter.error.AsusRouterAccessError: ('Access error', <AccessError.AUTHORIZATION: 2>, {}, None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/asusrouter/asusrouter.py", line 256, in async_api_load
    status, _, content = await self.async_api_query(endpoint, request)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/asusrouter/asusrouter.py", line 242, in async_api_query
    return await self._connection.async_query(endpoint, payload)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/asusrouter/connection.py", line 249, in async_query
    return await self._send_request(endpoint, payload, headers)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/asusrouter/connection.py", line 228, in _send_request
    raise ex
  File "/usr/local/lib/python3.11/site-packages/asusrouter/connection.py", line 217, in _send_request
    return handle_access_error(
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/asusrouter/modules/endpoint/error.py", line 60, in handle_access_error
    raise AsusRouterAccessError(
asusrouter.error.AsusRouterAccessError: ('Access error', <AccessError.AUTHORIZATION: 2>, {}, None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/asusrouter/asusrouter.py", line 256, in async_api_load
    status, _, content = await self.async_api_query(endpoint, request)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/asusrouter/asusrouter.py", line 242, in async_api_query
    return await self._connection.async_query(endpoint, payload)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/asusrouter/connection.py", line 249, in async_query
    return await self._send_request(endpoint, payload, headers)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/asusrouter/connection.py", line 228, in _send_request
    raise ex
  File "/usr/local/lib/python3.11/site-packages/asusrouter/connection.py", line 217, in _send_request
    return handle_access_error(
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/asusrouter/modules/endpoint/error.py", line 60, in handle_access_error
    raise AsusRouterAccessError(
asusrouter.error.AsusRouterAccessError: ('Access error', <AccessError.AUTHORIZATION: 2>, {}, None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/asusrouter/asusrouter.py", line 256, in async_api_load
    status, _, content = await self.async_api_query(endpoint, request)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/asusrouter/asusrouter.py", line 242, in async_api_query
    return await self._connection.async_query(endpoint, payload)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/asusrouter/connection.py", line 249, in async_query
    return await self._send_request(endpoint, payload, headers)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/asusrouter/connection.py", line 228, in _send_request
    raise ex
  File "/usr/local/lib/python3.11/site-packages/asusrouter/connection.py", line 217, in _send_request
    return handle_access_error(
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/asusrouter/modules/endpoint/error.py", line 60, in handle_access_error
    raise AsusRouterAccessError(
asusrouter.error.AsusRouterAccessError: ('Access error', <AccessError.AUTHORIZATION: 2>, {}, None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/asusrouter/asusrouter.py", line 256, in async_api_load
    status, _, content = await self.async_api_query(endpoint, request)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/asusrouter/asusrouter.py", line 242, in async_api_query
    return await self._connection.async_query(endpoint, payload)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/asusrouter/connection.py", line 249, in async_query
    return await self._send_request(endpoint, payload, headers)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/asusrouter/connection.py", line 228, in _send_request
    raise ex
  File "/usr/local/lib/python3.11/site-packages/asusrouter/connection.py", line 217, in _send_request
    return handle_access_error(
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/asusrouter/modules/endpoint/error.py", line 60, in handle_access_error
    raise AsusRouterAccessError(
```

**Comment by pergolafabio** [comment]
i also see 23.5 release now?

**Comment by Vaskivskyi** [comment]
Release `0.23.6` fixes the issue with an error loop. It is already available in HACS

If you will be experiencing any other issue, please open a new issue ticket
