### ISSUE TITLE
Setup unsuccessful

### ISSUE THREAD

**Issue by sezlony** [Vaskivskyi/ha-asusrouter#770]
### Anything you want to mention?

ok, here's what happened in chronological order:
1. upgraded straight to 0.28.0 from 0.23.0 (as far as I remember...)
2. uninstalled 28 and installed 26 (because many of the sensors didn't work anymore, missing)
3. uninstalled 26 and installed 23 manually (because 26 didn't work)
4. installed 28 without removing 23 (because it didn't work either)
5. uninstalled 23 and reinstalled 28 (because nothing really worked)

problems:
- configured as usual, but "**Failed setup, will retry**"
- integration does see "**No devices or entities**"
- during reconfiguration now I only can select "WAN" interface to monitor, no more options :(

I love this integration, I need this integration, but now all is messed up and can't solve it by myself - please PLEH...

### Your device model

RT-AC1200G+

### Firmware type

Stock

### Firmware version

3.0.0.4.382.52272

### Does everything work well?

Yes

**Comment by Vaskivskyi** [comment]
Hey,

The largest breaking changes were introduced in `0.23.0`, so it's weird you got to large troubles when upgrading. But this definitely should be fixable.

Can you please do the following:

1. Remove the integration (via HACS or manually, the same way you usually do)
2. Restart HA and install AsusRouter again.
3. Turn on debug logging for AsusRouter
4. Try to set up the integration with the usual settings you used (did you use SSL, by the way?)
5. Directly when setting up, go to the menu for selecting network interfaces. Is there only WAN available?
6. Finish the setup and check whether integration starts
7. Share your logs with Yevhenii@Vaskivskyi.com. You can also share them here if you wish, but they might contain the SN of your device as well as its MAC address

If you have such a possibility, you can try checking if the issue depends on any of the configurations of the integration

**Comment by sezlony** [comment]
1 and 2 is done, but "Unknown error" after entering credentials (just like in #769)

**Comment by Vaskivskyi** [comment]
Do you use SSL or non-SSL connection? If later, please try SSL connection (make sure HTTPS is enabled in the device settings)

**Comment by sezlony** [comment]
on SSL it is working without further errors, thank you for the advice! 👍

however the lack of sensors which were present on older versions is burning my heart 😢

**Comment by alrassia** [comment]
I had the same issue as described and ran through the suggested steps. The integration starts again, however when during the setup steps when trying to select the location of the devices it throws the error consistently.
I also noted than when I went to reconfigure, then on interfaces to monitor and selected WAN it started listing my router and nodes twice. I cannot also add a location to any of the devices without throwing the error.

The logs keep showing:
2024-01-09 12:41:32.056 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [139644949364416] Error handling message: Unknown error (unknown_error) usernameredacted from 192.168.50.xxx (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/connection.py", line 223, in async_handle
    handler(self.hass, self, schema(msg))
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 66, in with_admin
    func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/config/device_registry.py", line 89, in websocket_update_device
    entry = cast(DeviceEntry, registry.async_update_device(**msg))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/device_registry.py", line 751, in async_update_device
    self.devices[device_id] = new
    ~~~~~~~~~~~~^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/device_registry.py", line 416, in __setitem__
    del self._identifiers[identifier]
        ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
KeyError: ('asusrouter', '18:31:bf:48:c8:18')

**Comment by Vaskivskyi** [comment]
Sorry for the late reply.

I'll try to reproduce the issue and will get back to you with additional questions if needed

**Comment by sezlony** [comment]
for me the integration is working quite well! although I'm missing the sensors which were lost with the most recent version

**Comment by Vaskivskyi** [comment]
The connection issue is fixed, so I will close this one. It's rather complicated to track different issues when they are all together.

@sezlony, let's troubleshoot your sensors here #780 

---

@alrassia, please, [open a new issue](https://github.com/Vaskivskyi/ha-asusrouter/issues/new/choose) and provide the details about your device (model, FW) and all the details you think might be important to fix your problem. Then we can try to troubleshoot it
