### ISSUE TITLE
[Bug] Error

### ISSUE THREAD

**Issue by primski** [Vaskivskyi/ha-asusrouter#785]
### The problem

```
2024-02-03 15:04:52.047 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry 10.0.23.1 for asusrouter
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/config_entries.py", line 406, in async_setup
result = await component.async_setup_entry(hass, self)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/asusrouter/__init__.py", line 27, in async_setup_entry
await router.setup()
File "/config/custom_components/asusrouter/router.py", line 395, in setup
if "mac" in capabilities:
^^^^^^^^^^^^^^^^^^^^^
TypeError: argument of type 'NoneType' is not iterable
```

### Your device model

RT-AC88U

### Firmware type

Stock

### Firmware version

386.12_4

### Integration version with the issue

Firmware: 3.0.0.4.386.12_4

### Method of the integration installation

HACS

### What version and type of Home Assistant installation do you use

Firmware: 3.0.0.4.386.12_4

**Comment by Vaskivskyi** [comment]
Hello. Sorry to hear that you are experiencing issues.

It will be fixed in PR #786 and the fix will be available in the next release
