### ISSUE TITLE
Integration not loading after 2024.2.1

### ISSUE THREAD

**Issue by hossihub** [Vaskivskyi/ha-asusrouter#798]
### The problem

Upgraded integration and it wont launch after upgrading to 2024.2.1

### Your device model

RT-AX86U

### Firmware type

Stock

### Firmware version

3004.388.6 S

### Integration version with the issue

0.29.0

### Method of the integration installation

HACS

### What version and type of Home Assistant installation do you use

2024.2.1

### Is there anything useful in the logs?

```txt
Logger: homeassistant.config_entries
Source: config_entries.py:2275
First occurred: 21:47:15 (16 occurrences)
Last logged: 21:50:05

Error occurred loading flow for integration asusrouter: Exception importing custom_components.asusrouter.config_flow

Logger: homeassistant.loader
Source: loader.py:847
First occurred: 21:47:15 (16 occurrences)
Last logged: 21:50:05

Unexpected exception importing platform custom_components.asusrouter.config_flow
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 847, in get_platform
    cache[full_name] = self._import_platform(platform_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 864, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1310, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 994, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/asusrouter/__init__.py", line 12, in <module>
    from .const import ASUSROUTER, DOMAIN, PLATFORMS, STOP_LISTENER
  File "/config/custom_components/asusrouter/const.py", line 972, in <module>
    state=AsusSystem.RESTART_NET,
          ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: type object 'AsusSystem' has no attribute 'RESTART_NET'. Did you mean: 'RESTART_LEDS'?
```

**Comment by hossihub** [comment]
reloaded from HACS and it now works after reboot.

**Comment by Vaskivskyi** [comment]
Looks like you somehow got the new version working without HA updating the backend library to the latest version. Good, that it's solved. In principle, this should not happen, since Home Assistant should check and install all the dependencies for the integrations automatically
