### ISSUE TITLE
AsusRouter Integration doesn't reload automatically upon HA reboot [Bug] 

### ISSUE THREAD

**Issue by bfish2** [Vaskivskyi/ha-asusrouter#841]
### The problem

For the past several months, when I have restarted HA, I have had to manually press reload on the entries for each AP in the integration in order to get it to fully load.  More recently (past few weeks), I have had to press reload many times (up to 10 or more) on each entry in order to get them to fully load.  Once loaded, the integration seems to be working OK.

### Your device model

RT-AX92U

### Firmware type

Stock

### Firmware version

3.0.0.4.388_23630

### Integration version with the issue

0.32.1

### Method of the integration installation

HACS

### What version and type of Home Assistant installation do you use

Core 20242.6.3

### Is there anything useful in the logs?

```txt
Logger: homeassistant.config_entries
Source: config_entries.py:594
First occurred: 8:17:01 AM (12 occurrences)
Last logged: 8:24:22 AM

Error setting up entry 192.168.86.1 for asusrouter
Error setting up entry 192.168.86.249 for asusrouter
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 594, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/asusrouter/__init__.py", line 27, in async_setup_entry
    await router.setup()
  File "/config/custom_components/asusrouter/router.py", line 363, in setup
    device_registry.async_remove_device(device_entry.id)
  File "/usr/src/homeassistant/homeassistant/helpers/device_registry.py", line 947, in async_remove_device
    device = self.devices.pop(device_id)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen _collections_abc>", line 951, in pop
  File "/usr/src/homeassistant/homeassistant/helpers/registry.py", line 62, in __delitem__
    self._unindex_entry(key)
  File "/usr/src/homeassistant/homeassistant/helpers/device_registry.py", line 543, in _unindex_entry
    super()._unindex_entry(key, replacement_entry)
  File "/usr/src/homeassistant/homeassistant/helpers/device_registry.py", line 484, in _unindex_entry
    del self._identifiers[identifier]
        ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
KeyError: ('asusrouter', '04:42:1a:6a:2d:20')
```

### Diagnostics information

[syslog.txt](https://github.com/user-attachments/files/15901079/syslog.txt)

**Comment by Vaskivskyi** [comment]
Hello, @bfish2. Thanks for your feedback and sorry for the issues you are experiencing. I will check this

**Comment by yuejon** [comment]
I also have this issue and my workaround has been to use an automation which loops and reloads the config until the integration is back online, whenever HA is restarted. Definitely would prefer a permanent fix in the integration itself, but this workaround at least lets me not have to constantly reload it manually after a restart.

```
alias: "Network: Reload AsusRouter integration on start"
description: ""
trigger:
  - platform: homeassistant
    event: start
condition: []
action:
  - delay:
      hours: 0
      minutes: 5
      seconds: 0
      milliseconds: 0
  - alias: Reload Asus ZenWiFi Router Config
    repeat:
      sequence:
        - service: homeassistant.reload_config_entry
          data: {}
          target:
            entity_id: sensor.asus_zenwifi_boot_time
        - delay:
            hours: 0
            minutes: 0
            seconds: 30
            milliseconds: 0
      while:
        - condition: and
          conditions:
            - condition: state
              entity_id: sensor.asus_zenwifi_boot_time
              state: unavailable
mode: single
```

**Comment by matt0020190** [comment]
Hi, just to report I have exactly the same issue. Eventually the integration reloads but it takes several attempts. Any update?

**Comment by bitlisz1** [comment]
Same issue here with 2 pcs of RT-AX92U, and mesh router unavaiable, always need to reload integration.

**Comment by micdesa** [comment]
Same here

**Comment by bitlisz1** [comment]
> Same issue here with 2 pcs of RT-AX92U, and mesh router unavaiable, always need to reload integration.

Sometimes Main router:

```
Logger: homeassistant.config_entries
Source: config_entries.py:604
First occurred: 10:38:17 AM (1 occurrences)
Last logged: 10:38:17 AM

Error setting up entry 192.168.1.1 for asusrouter
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 604, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/asusrouter/__init__.py", line 27, in async_setup_entry
    await router.setup()
  File "/config/custom_components/asusrouter/router.py", line 370, in setup
    device_registry.async_remove_device(device_entry.id)
  File "/usr/src/homeassistant/homeassistant/helpers/device_registry.py", line 1141, in async_remove_device
    device = self.devices.pop(device_id)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen _collections_abc>", line 951, in pop
  File "/usr/src/homeassistant/homeassistant/helpers/registry.py", line 62, in __delitem__
    self._unindex_entry(key)
  File "/usr/src/homeassistant/homeassistant/helpers/device_registry.py", line 613, in _unindex_entry
    super()._unindex_entry(key, replacement_entry)
  File "/usr/src/homeassistant/homeassistant/helpers/device_registry.py", line 554, in _unindex_entry
    del self._identifiers[identifier]
        ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
KeyError: ('asusrouter', None)
```

**Comment by bitlisz1** [comment]
It is very frequent.
Added some debug log (replaced/removed all mac/ip and others).

[home-assistant_2024-10-22T11-23-03.348Z.log](https://github.com/user-attachments/files/17475624/home-assistant_2024-10-22T11-23-03.348Z.log)

**Comment by bitlisz1** [comment]
[home-assistant_2024-10-22T11-23-03.348Z.log](https://github.com/user-attachments/files/17475775/home-assistant_2024-10-22T11-23-03.348Z.log)

**Comment by bitlisz1** [comment]
Any home to fix this?

**Comment by Vaskivskyi** [comment]
Hello. I am really sorry for such a long delay to get back to you. I did not have time to work on AsusRouter lately due to some other obligations.

Allow me to check the issue till the end of the week (Jan 19, 2025). If there won't be any update from my side till that time, please, tag me again here using `@vaskivskyi` (without code quotes)

**Comment by bitlisz1** [comment]
@Vaskivskyi Would you be so kind to check this?

**Comment by bitlisz1** [comment]
@vaskivskyi Could you check this? I had to reload Hubs every time after HA need to restart because of updates.

I several times tried to write automation to reload config entry when state: unavailable, but does not work...

**Comment by Vaskivskyi** [comment]
Please, check wether the issue persists with version `0.35.0` of the integration. If so, please, provide any error trace available in your log corresponding to `asusrouter`. Thanks!

List all the devices you have in your network (even those which work well if any) and whether the issue is always with some exact device(s) or is it random and e.g. 2 of 3 always fail but not the same 2 every time

**Comment by bitlisz1** [comment]
Issue persist with version 0.35.0 of the integration too.

I have 3 routers:
192.168.1.1 -> RT-AX92U - Main router
192.168.1.146 -> RT-AX92U - AiMesh node with wired backhaul
192.168.1.233 -> XD6S - Wireless Media bridge (on 5Ghz)

Only occured always with Main and Mesh roouter: RT-AX92U
Each had several firmwares, right now with latest: 3.0.0.4.388_23712
After HA restart always fail to load.
Under asusrouter integration need to reload each Hubs 3-5 times to succesfully reload.

Last log after installed 0.35.0 and restarted:
(also enabled debug logging, attached:
[home-assistant_asusrouter_2025-03-23T23-17-04.998Z.log](https://github.com/user-attachments/files/19412082/home-assistant_asusrouter_2025-03-23T23-17-04.998Z.log)

`Logger: homeassistant.config_entries
Source: config_entries.py:753
First occurred: 12:09:44 AM (2 occurrences)
Last logged: 12:09:44 AM

Error setting up entry 192.168.1.146 for asusrouter
Error setting up entry 192.168.1.1 for asusrouter
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 753, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/asusrouter/__init__.py", line 27, in async_setup_entry
    await router.setup()
  File "/config/custom_components/asusrouter/router.py", line 370, in setup
    device_registry.async_remove_device(device_entry.id)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/device_registry.py", line 1251, in async_remove_device
    device = self.devices.pop(device_id)
  File "<frozen _collections_abc>", line 956, in pop
  File "/usr/src/homeassistant/homeassistant/helpers/registry.py", line 62, in __delitem__
    self._unindex_entry(key)
    ~~~~~~~~~~~~~~~~~~~^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/device_registry.py", line 654, in _unindex_entry
    super()._unindex_entry(key, replacement_entry)
    ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/device_registry.py", line 580, in _unindex_entry
    del self._identifiers[identifier]
        ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
KeyError: ('asusrouter', '**:**:**:**:**:**')`

**Comment by kajmaj** [comment]
Any progress? 
integration version 0.35.0
router DSL-AC68U
still the same behavior.
