### ISSUE TITLE
[Device support] ASUS GT-BE98 Intergration Failure at HA Reboot

### ISSUE THREAD

**Issue by JYChong92** [Vaskivskyi/ha-asusrouter#849]
### Anything you want to mention?

Everytime the HA reboots, ASUS Router intergration will fails and it directs me to the log file.
Below are the log file extracted after the error message appear.

2024-08-18 17:51:26.366 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry GT-BE98 for asusrouter
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 604, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/asusrouter/__init__.py", line 27, in async_setup_entry
    await router.setup()
  File "/config/custom_components/asusrouter/router.py", line 329, in setup
    await self.bridge.async_connect()
  File "/config/custom_components/asusrouter/bridge.py", line 149, in async_connect
    await self.api.async_connect()
  File "/usr/local/lib/python3.12/site-packages/asusrouter/asusrouter.py", line 135, in async_connect
    return await self.async_get_identity() is not None
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/asusrouter/asusrouter.py", line 221, in async_get_identity
    self._identity = await collect_identity(
                     ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/asusrouter/modules/identity.py", line 115, in collect_identity
    endpoints, onboarding = await _check_endpoints(api_query)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/asusrouter/modules/identity.py", line 210, in _check_endpoints
    onboarding = process_onboarding(
                 ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/asusrouter/modules/endpoint/onboarding.py", line 84, in process
    convert = process_connection(connection)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/asusrouter/modules/endpoint/onboarding.py", line 158, in process_connection
    "guest": int(temp[1]) if len(temp) > 1 else 0,
             ^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: 'info'

### Your device model

GT-BE98

### Firmware type

Stock

### Firmware version

3.0.0.6.102_34372

### Does everything work well?

No

**Comment by Vaskivskyi** [comment]
Hello, @JYChong92, sorry for the delay. PR in the backend library is fixing the issue. An update to the integration will be available later this week together with other changes

**Comment by JYChong92** [comment]
Hi @Vaskivskyi,
Thanks for going through the fixes!
I will give it a try again once the fixes are available.

Thanks again for all the hard work and love your creation here that really really really helps me a lot with the integration of ASUS router to HA environment!

**Comment by Vaskivskyi** [comment]
The issue should be fixed with the new version `0.33.2` of the integration
