### ISSUE TITLE
[Bug] New errors on 0.33.1

### ISSUE THREAD

**Issue by a-lunatic** [Vaskivskyi/ha-asusrouter#862]
### The problem

3 new errors

### Your device model

RT-AC88U

### Firmware type

Merlin

### Firmware version

 386.14

### Integration version with the issue

0.33.1

### Method of the integration installation

HACS

### What version and type of Home Assistant installation do you use

2024.8.3

### Is there anything useful in the logs?

```txt
This error originated from a custom integration.

Logger: custom_components.asusrouter.router
Source: helpers/update_coordinator.py:354
integration: AsusRouter (documentation, issues)
First occurred: 21:12:58 (1 occurrences)
Last logged: 21:12:58

Unexpected error fetching firmware data
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 354, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 271, in _async_update_data
    return await self.update_method()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/asusrouter/bridge.py", line 350, in _get_data_firmware
    data = await self._get_data_modern(AsusData.FIRMWARE)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/asusrouter/bridge.py", line 312, in _get_data_modern
    raw = await self.api.async_get_data(datatype, force=force)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/asusrouter/asusrouter.py", line 705, in async_get_data
    processed = process(
                ^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/asusrouter/modules/endpoint/__init__.py", line 149, in process
    return submodule.process(data)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/asusrouter/modules/endpoint/firmware.py", line 27, in process
    _available = Firmware(data.get("webs_state_info", "")).safe()
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/asusrouter/modules/firmware.py", line 86, in __init__
    self.from_string(version)
  File "/usr/local/lib/python3.12/site-packages/asusrouter/modules/firmware.py", line 169, in from_string
    beta = major[0] == "9"
           ~~~~~^^^
TypeError: 'NoneType' object is not subscriptable





Logger: homeassistant.components.device_tracker
Source: helpers/entity_platform.py:775
integration: Device Tracker (documentation, issues)
First occurred: 21:12:58 (8 occurrences)
Last logged: 21:12:58

asusrouter: Not adding entity with invalid device info: Invalid device info {'connections': {('mac', 'XX:XX:XX:XX:XX:XX')}, 'default_name': 'XX', 'identifiers': {('asusrouter', 'XX:XX:XX:XX:XX:XX')}, 'via_device': ('asusrouter', 'XX:XX:XX:XX:XX:XX')} for 'asusrouter' config entry: device info needs to either describe a device, link to existing device or provide extra information.
asusrouter: Not adding entity with invalid device info: Invalid device info {'connections': {('mac', 'XX:XX:XX:XX:XX:XX')}, 'default_name': 'XX', 'identifiers': {('asusrouter', 'XX:XX:XX:XX:XX:XX')}, 'via_device': ('asusrouter', 'XX:XX:XX:XX:XX:XX')} for 'asusrouter' config entry: device info needs to either describe a device, link to existing device or provide extra information.
asusrouter: Not adding entity with invalid device info: Invalid device info {'connections': {('mac', 'XX:XX:XX:XX:XX:XX')}, 'default_name': 'XX', 'identifiers': {('asusrouter', 'XX:XX:XX:XX:XX:XX')}, 'via_device': ('asusrouter', 'XX:XX:XX:XX:XX:XX')} for 'asusrouter' config entry: device info needs to either describe a device, link to existing device or provide extra information.
asusrouter: Not adding entity with invalid device info: Invalid device info {'connections': {('mac', 'XX:XX:XX:XX:XX:XX')}, 'default_name': 'XX', 'identifiers': {('asusrouter', 'XX:XX:XX:XX:XX:XX')}, 'via_device': ('asusrouter', 'XX:XX:XX:XX:XX:XX')} for 'asusrouter' config entry: device info needs to either describe a device, link to existing device or provide extra information.
asusrouter: Not adding entity with invalid device info: Invalid device info {'connections': {('mac', 'XX:XX:XX:XX:XX:XX')}, 'default_name': 'XX', 'identifiers': {('asusrouter', 'XX:XX:XX:XX:XX:XX')}, 'via_device': ('asusrouter', 'XX:XX:XX:XX:XX:XX')} for 'asusrouter' config entry: device info needs to either describe a device, link to existing device or provide extra information.





This error originated from a custom integration.

Logger: custom_components.asusrouter.entity
Source: custom_components/asusrouter/entity.py:65
integration: AsusRouter (documentation, issues)
First occurred: 21:12:58 (2 occurrences)
Last logged: 21:12:58

argument of type 'NoneType' is not iterable
```

**Comment by Vaskivskyi** [comment]
Please, check `0.33.2`. It fixes your issue with the firmware string (which is somehow missing the `major` version part. The device trackers are also fixed now

As per the last one (which is a warning) - logging was improved, so now you'll see what exactly entity cannot be created. Then we can troubleshoot or fix something more

Let me know what you find

**Comment by a-lunatic** [comment]
All good now.

**Comment by Vaskivskyi** [comment]
Great :+1:
