### ISSUE TITLE
[Bug] Not being set up. ImportError

### ISSUE THREAD

**Issue by rainepretorius** [Vaskivskyi/ha-asusrouter#871]
### The problem

Logger: homeassistant.setup
Source: setup.py:334
First occurred: 13:51:17 (1 occurrences)
Last logged: 13:51:17

Setup failed for custom integration 'asusrouter': Unable to import component: No module named 'asusrouter.modules.color'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 334, in _async_setup_component
    component = await integration.async_get_component()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1027, in async_get_component
    self._component_future.result()
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1007, in async_get_component
    comp = await self.hass.async_add_import_executor_job(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1067, in _get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 200, in protected_loop_func
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/asusrouter/__init__.py", line 13, in <module>
    from .router import ARDevice
  File "/config/custom_components/asusrouter/router.py", line 35, in <module>
    from .bridge import ARBridge
  File "/config/custom_components/asusrouter/bridge.py", line 72, in <module>
    from .modules.aura import aura_to_ha
  File "/config/custom_components/asusrouter/modules/aura.py", line 15, in <module>
    from asusrouter.modules.color import ColorRGBB
ModuleNotFoundError: No module named 'asusrouter.modules.color'

### Your device model

RT-AX58U

### Firmware type

Stock

### Firmware version

3.0.0.4.388_24762

### Integration version with the issue

0.34.0

### Method of the integration installation

HACS

### What version and type of Home Assistant installation do you use

Core 2024.8.2

### Is there anything useful in the logs?

```txt
Logger: homeassistant.setup
Source: setup.py:334
First occurred: 13:51:17 (1 occurrences)
Last logged: 13:51:17

Setup failed for custom integration 'asusrouter': Unable to import component: No module named 'asusrouter.modules.color'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 334, in _async_setup_component
    component = await integration.async_get_component()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1027, in async_get_component
    self._component_future.result()
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1007, in async_get_component
    comp = await self.hass.async_add_import_executor_job(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1067, in _get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 200, in protected_loop_func
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/asusrouter/__init__.py", line 13, in <module>
    from .router import ARDevice
  File "/config/custom_components/asusrouter/router.py", line 35, in <module>
    from .bridge import ARBridge
  File "/config/custom_components/asusrouter/bridge.py", line 72, in <module>
    from .modules.aura import aura_to_ha
  File "/config/custom_components/asusrouter/modules/aura.py", line 15, in <module>
    from asusrouter.modules.color import ColorRGBB
ModuleNotFoundError: No module named 'asusrouter.modules.color'
```

**Comment by Vaskivskyi** [comment]
Hello, @rainepretorius,

It looks like something went wrong with the installation of the backend library when you upgraded the integration. The module which is reported should be available there from the integration version `0.33.0` already.

Did you update from `0.32.x` or older?

Please, try just restarting the Home Assistant fully. It should check the dependencies on the startup and reinstall them if anything is missing or was not updated correctly

**Comment by rainepretorius** [comment]
Hi,

I did upgrade from 0.32. I downgraded back to 0.31 as rhat was the last 100% stable version

**Comment by Vaskivskyi** [comment]
Unfortunately, there is no way I can help you then.

If you are still planning on upgrading to `0.34.0`, please, make sure you did all of the following steps:

- Installed the new version from HACS or manually from the GitHub `main` branch
- Restarted your Home Assistant instance
- Checked the log for any issue with the requirements, e.g.

![image](https://github.com/user-attachments/assets/661a8965-ec36-4af8-81e9-1e1283f91c15)

If it still fails with the same issue of importing a module from the backend, we can start performing further troubleshooting, including the manual check of whether pip installed the backend correctly and if not, why.

E.g. if you are using HA Core and have access to the venv in which HA runs, you can use `pip show asusrouter` or `python3 -m pip show asusrouter` which should report which version is installed. For integration version `0.34.0` in should be `1.13.0` or `1.12.x` for versions `0.33.x` of the integration. If not, you can try manually install the package with `python3 -m pip install asusrouter==1.13.0`. If it gives you any errors - we'll know the reason.

**Comment by Vaskivskyi** [comment]
If you would like to continue with the troubleshooting, please, reopen this issue
