### ISSUE TITLE
[Bug] Unable to install package

### ISSUE THREAD

**Issue by kribjo** [Vaskivskyi/ha-asusrouter#894]
### The problem

I can't add the integration, "Config flow could not be loaded: 500 Internal Server Error Server got itself in trouble" (see below for full error report), but when I look in the logs it seems that there is an issue earlier in the chain of events, see below:

> Unable to install package asusrouter==1.13.1: error: Failed to fetch: `https://wheels.home-assistant.io/musllinux-index/asusrouter/` Caused by: Could not connect, are you offline? Caused by: Request failed after 3 retries Caused by: error sending request for url (https://wheels.home-assistant.io/musllinux-index/asusrouter/) Caused by: client error (Connect) Caused by: dns error: failed to lookup address information: Try again Caused by: failed to lookup address information: Try again

It says something about DNS error, but when I go to the https://wheels.home-assistant.io/musllinux-index/asusrouter/ there is no DNS problem, but there also is nothing there to fetch ("404 Not Found"). Is this expected?!

Full error report for the error when trying to add the integration:

> Logger: aiohttp.server
> Source: /usr/local/lib/python3.13/site-packages/aiohttp/web_protocol.py:451
> First occurred: 12:39:48 AM (1 occurrences)
> Last logged: 12:39:48 AM
> 
> Error handling request
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.13/site-packages/aiohttp/web_protocol.py", line 480, in _handle_request
>     resp = await request_handler(request)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.13/site-packages/aiohttp/web_app.py", line 569, in _handle
>     return await handler(request)
>            ^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.13/site-packages/aiohttp/web_middlewares.py", line 117, in impl
>     return await handler(request)
>            ^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 92, in security_filter_middleware
>     return await handler(request)
>            ^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 83, in forwarded_middleware
>     return await handler(request)
>            ^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 26, in request_context_middleware
>     return await handler(request)
>            ^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 86, in ban_middleware
>     return await handler(request)
>            ^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 242, in auth_middleware
>     return await handler(request)
>            ^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/src/homeassistant/homeassistant/components/http/headers.py", line 32, in headers_middleware
>     response = await handler(request)
>                ^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/src/homeassistant/homeassistant/helpers/http.py", line 73, in handle
>     result = await handler(request, **request.match_info)
>              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/src/homeassistant/homeassistant/components/http/decorators.py", line 81, in with_admin
>     return await func(self, request, *args, **kwargs)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 74, in wrapper
>     return await method(view, request, data, *args, **kwargs)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 172, in post
>     return await self._post_impl(request, data)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 179, in _post_impl
>     return await super()._post_impl(request, data)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 84, in _post_impl
>     result = await self._flow_mgr.async_init(
>              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>     ...<2 lines>...
>     )
>     ^
>   File "/usr/src/homeassistant/homeassistant/config_entries.py", line 1315, in async_init
>     flow, result = await self._async_init(flow_id, handler, context, data)
>                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/src/homeassistant/homeassistant/config_entries.py", line 1340, in _async_init
>     flow = await self.async_create_flow(handler, context=context, data=data)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/src/homeassistant/homeassistant/config_entries.py", line 1536, in async_create_flow
>     handler = await _async_get_flow_handler(
>               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>         self.hass, handler_key, self._hass_config
>         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>     )
>     ^
>   File "/usr/src/homeassistant/homeassistant/config_entries.py", line 3333, in _async_get_flow_handler
>     await _load_integration(hass, domain, hass_config)
>   File "/usr/src/homeassistant/homeassistant/config_entries.py", line 3310, in _load_integration
>     await async_process_deps_reqs(hass, hass_config, integration)
>   File "/usr/src/homeassistant/homeassistant/setup.py", line 575, in async_process_deps_reqs
>     await requirements.async_get_integration_with_requirements(
>         hass, integration.domain
>     )
>   File "/usr/src/homeassistant/homeassistant/requirements.py", line 54, in async_get_integration_with_requirements
>     return await manager.async_get_integration_with_requirements(domain)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/src/homeassistant/homeassistant/requirements.py", line 170, in async_get_integration_with_requirements
>     await future
>   File "/usr/src/homeassistant/homeassistant/requirements.py", line 159, in async_get_integration_with_requirements
>     await self._async_process_integration(integration, done)
>   File "/usr/src/homeassistant/homeassistant/requirements.py", line 182, in _async_process_integration
>     await self.async_process_requirements(
>         integration.domain, integration.requirements
>     )
>   File "/usr/src/homeassistant/homeassistant/requirements.py", line 264, in async_process_requirements
>     self._raise_for_failed_requirements(name, missing)
>     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
>   File "/usr/src/homeassistant/homeassistant/requirements.py", line 292, in _raise_for_failed_requirements
>     raise RequirementsNotFound(integration, [req])
> homeassistant.requirements.RequirementsNotFound: Requirements for asusrouter not found: ['asusrouter==1.13.1'].

### Your device model

GT-AX6000

### Firmware type

Merlin

### Firmware version

3004.388.8_4

### Integration version with the issue

0.34.1/1.13.1

### Method of the integration installation

HACS

### What version and type of Home Assistant installation do you use

Core 2024.12.5

**Comment by Vaskivskyi** [comment]
Hello. I am really sorry for such a long delay to get back to you. I did not have time to work on AsusRouter lately due to some other obligations.

Allow me to check the issue till the end of the week (Jan 19, 2025). If there won't be any update from my side till that time, please, tag me again here using `@vaskivskyi` (without code quotes)

**Comment by Vaskivskyi** [comment]
Hello. The issue reported here is not connected to the integration, but rather to the HA installation itself (which somewhy was not installing the package from the Python Package Index, but tried finding it in the list of HA wheels).

Currently, since the HA version has already been updated several times, I will close the issue. If you still cannot use AsusRouter due to the library installation bugs, please add to the new universal issue report #920 and we can solve this for your current conditions
